import { MoreHorizontal, RefreshCw } from "lucide-react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { useRepository } from "../repository-context.tsx";
import { Status } from "./student-dashboard.tsx";

export function OperationsDashboard(){
  const repository=useRepository();const {t}=useTranslation();const client=useQueryClient();const dashboard=useQuery({queryKey:["dashboard"],queryFn:()=>repository.dashboard(),refetchInterval:15_000});const courseId=dashboard.data?.course.id;const operations=useQuery({queryKey:["course-operations",courseId],queryFn:()=>repository.courseOperations(courseId!),enabled:Boolean(courseId),refetchInterval:15_000});
  const [stage,setStage]=useState("all");const [status,setStatus]=useState("all");const [attention,setAttention]=useState("all");const [message,setMessage]=useState("");const projects=operations.data?.projects??[];const filtered=useMemo(()=>projects.filter(project=>(stage==="all"||project.stage_key===stage)&&(status==="all"||project.latest_run_status===status)&&(attention==="all"||attention==="appeal"&&project.open_appeals>0||attention==="failed"&&project.failed_runs>0)),[projects,stage,status,attention]);
  if(!dashboard.data)return <div className="page-loading">{t("正在加载课程运营工作台…")}</div>;const data=dashboard.data;const pending=projects.filter(project=>project.failed_runs>0||project.open_appeals>0);const stages=[...new Set(projects.map(project=>project.stage_key))];
  async function rerun(){const run=data.runs.find(item=>["failed","cancelled","timed_out"].includes(item.status));if(!run)return;setMessage("");try{await repository.review({run_id:run.id,action:"rerun",reason:"teacher approved a controlled assessment rerun"});setMessage(t("补跑已创建并写入审计记录。"));await client.invalidateQueries();}catch(error){setMessage(error instanceof Error?error.message:String(error));}}
  return <main className="page teacher-home">
    <div className="teacher-title"><div><p>{data.course.code} · {data.course.term}</p><h1>{t("课程运营")}</h1></div><span className="live"><i/>{t("15 秒刷新")} <RefreshCw/></span></div>
    <section className="course-lifecycle" aria-label={t("课程生命周期")}>{["draft","published","active","grading","appeal","closed"].map((item,index)=><div className={item===data.course.status?"current":index<["draft","published","active","grading","appeal","closed"].indexOf(data.course.status)?"done":""} key={item}><i>{index+1}</i><span>{t(item)}</span></div>)}</section>
    <section className="pending-strip"><div><b>{t("待办")}</b><span>{t("{{projects}} 个项目需要处理",{projects:pending.length})}</span><span>{pending.reduce((sum,item)=>sum+item.failed_runs,0)} {t("次失败")}</span><span>{pending.reduce((sum,item)=>sum+item.open_appeals,0)} {t("个申诉")}</span></div><button className="button primary" type="button" disabled={!data.runs.some(run=>["failed","cancelled","timed_out"].includes(run.status))} onClick={()=>void rerun()}>{t("处理首项")}</button></section>
    {message?<p className="operation-message" role="status">{message}</p>:null}
    <section className="teacher-filters" aria-label={t("项目筛选")}><label>{t("阶段")}<select value={stage} onChange={event=>setStage(event.target.value)}><option value="all">{t("全部阶段")}</option>{stages.map(item=><option key={item}>{item}</option>)}</select></label><label>{t("运行状态")}<select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">{t("全部状态")}</option><option value="passed">{t("通过")}</option><option value="failed">{t("失败")}</option><option value="running">{t("运行中")}</option></select></label><label>{t("需要关注")}<select value={attention} onChange={event=>setAttention(event.target.value)}><option value="all">{t("全部项目")}</option><option value="failed">{t("存在失败")}</option><option value="appeal">{t("开放申诉")}</option></select></label></section>
    <section className="surface project-table"><header><h2>{t("项目")}</h2><small>{filtered.length} / {projects.length}</small></header><div className="table-wrap"><table><thead><tr><th>{t("项目与成员")}</th><th>{t("阶段")}</th><th>{t("最新测评")}</th><th>{t("成绩")}</th><th>{t("待处理")}</th><th>{t("操作")}</th></tr></thead><tbody>{filtered.map(project=><tr key={project.project_id}><td><b>{project.project_id}</b><small>{project.member_names.join("、")||"—"}</small></td><td>{project.stage_name}</td><td>{project.latest_run_status?<Status value={project.latest_run_status}/>:"—"}</td><td>{project.score_state?`${t(project.score_state)}${project.final_score===undefined?"":` · ${project.final_score.toFixed(1)}`}`:"—"}</td><td>{project.failed_runs?`${project.failed_runs} ${t("失败")}`:project.open_appeals?`${project.open_appeals} ${t("申诉")}`:"—"}</td><td><Link className="button primary" to="/operations">{t("复核")}</Link><button className="icon-button" aria-label={t("更多项目操作")}><MoreHorizontal/></button></td></tr>)}{!filtered.length?<tr><td colSpan={6}>{t("没有符合筛选条件的项目。")}</td></tr>:null}</tbody></table></div></section>
    <div className="teacher-bottom"><section className="surface stage-distribution"><header><h2>{t("阶段分布")}</h2></header>{stages.map(item=>{const count=projects.filter(project=>project.stage_key===item).length;return <div key={item}><span>{item}</span><progress max={Math.max(projects.length,1)} value={count}/><b>{count}</b></div>})}</section><section className="surface recent-events"><header><h2>{t("近期事件")}</h2></header>{data.runs.slice(0,5).map(run=><article key={run.id}><Status value={run.status}/><div><b>{run.stage_key} · {run.commit_sha.slice(0,8)}</b><small>{new Date(run.created_at).toLocaleString()}</small></div><Link to={`/runs/${run.id}`}>{t("查看")}</Link></article>)}</section></div>
  </main>;
}
