import {
  AppealSubmitV1Schema, AppealTransitionV1Schema, CourseGroupMutationV1Schema, CourseManifestV1Schema, DesignReviewInputV1Schema, DesignSubmissionInputV1Schema, EnrollmentCsvImportV1Schema, EnrollmentInviteCreateV1Schema, EnrollmentInviteRedeemV1Schema, PipelineRequestV1Schema, ProjectProvisionRequestV1Schema, RetentionPolicyUpdateV1Schema, ScoreAdjustmentInputV1Schema, ScoreCalculationV1Schema, ScoreTransitionV1Schema, type AgentAuditV1, type AppealRecordV1, type AppealSubmitV1, type AppealTransitionV1, type CourseGroupMutationV1, type CourseGroupV1, type CourseManifestDryRunV1, type CourseManifestV1, type CourseManifestVersionV1, type DesignReviewInputV1, type DesignSubmissionInputV1, type DesignSubmissionV1, type EnrollmentCsvImportV1, type EnrollmentImportResultV1, type EnrollmentInviteCreateV1, type EnrollmentInviteIssuedV1, type EnrollmentInviteRedeemV1, type EnrollmentInviteRedemptionV1, type EnrollmentInviteSummaryV1, type PipelineRequestV1, type PortalActor,
  ModelProviderInputV1Schema, ModelQuotaPolicyInputV1Schema, type ModelCredentialInputV1, type ModelCredentialRefV1, type ModelProviderInputV1, type ModelProviderSummaryV1, type ModelQuotaPolicyInputV1, type ModelQuotaPolicyV1, type NotificationV1, type OidcProviderInputV1, type OidcProviderSummaryV1, type PortalDashboard, type PortalRole, type ProjectProvisionOptionsV1, type ProjectProvisionRequestV1, type ProjectProvisionStatusV1, type QaThreadV1, type RetentionPolicyUpdateV1, type RetentionPolicyV1, type ScoreAdjustmentInputV1, type ScoreCalculationV1, type ScoreSnapshotV1, type ScoreTransitionV1,
} from "vos-core/portal-contracts";
import type { AdminSystemStatusV1 } from "vos-core/portal-contracts";
import type { LoginInput, PortalRepository, ReviewInput } from "../domain/repository.ts";
import { assertStaff, assertTeacher } from "../domain/repository.ts";
import { createDemoDashboard, createEvidence, createQaThread, demoActors } from "./seed.ts";
import { parseEnrollmentCsv } from "../domain/enrollment-csv.ts";
import { transitionCourse as applyCourseTransition, type CourseState } from "../domain/state-machines.ts";

const STORAGE_KEY = "vos-portal.demo.v1";
const SCHEMA_VERSION = 10;
interface DemoInvite extends EnrollmentInviteSummaryV1 { code:string; redeemed_user_ids:string[] }
interface DemoState { schema_version: 10; signed_in:boolean; dashboard: PortalDashboard; qa: QaThreadV1; appeals: AppealRecordV1[]; scores:ScoreSnapshotV1[]; provisions:ProjectProvisionStatusV1[]; course_versions:CourseManifestVersionV1[]; enrollment_imports:EnrollmentImportResultV1[]; invites:DemoInvite[]; course_groups:CourseGroupV1[]; designs:DesignSubmissionV1[]; retention:RetentionPolicyV1; model_providers:ModelProviderSummaryV1[]; model_quotas:ModelQuotaPolicyV1[] }

function initialState(): DemoState { const dashboard=createDemoDashboard();const now="2026-05-16T08:40:00.000Z";return { schema_version: SCHEMA_VERSION,signed_in:true, dashboard, qa: createQaThread(), appeals: [],scores:[dashboard.score],provisions:[],course_versions:[],enrollment_imports:[],invites:[],course_groups:[{version:"course-group.v1",id:"group-demo-3",course_id:dashboard.course.id,name:"第 03 组",member_ids:[demoActors.student.id],revision:1,created_at:now,updated_at:now}],designs:[{version:"design-submission.v1",id:"design-demo-1",project_id:dashboard.project.project_id,stage_key:dashboard.project.current_stage.key,commit_sha:dashboard.runs[0]?.commit_sha??"a".repeat(40),revision:1,title:"内存映射与 TLB 一致性设计",summary:"将页表修改、跨核失效通知与完成屏障组织为可验证的单向状态转换。",invariants:["释放物理页前，所有相关 hart 必须确认旧 TLB 项已经失效。","页表写入必须先于跨核失效请求对其他 hart 可见。"],interfaces:[{name:"vm_unmap",contract:"移除页表项并在返回前完成相关 hart 的 TLB 失效确认。"}],evidence_refs:[dashboard.runs[0]?.id??"run-demo"],status:"submitted",submitted_by:demoActors.student.id,created_at:now,updated_at:now}],retention:{version:"retention-policy.v1",ordinary_days:30,records_days:365,revision:1,updated_at:now},model_providers:[{version:"model-provider-summary.v1",id:"school-model-demo",name:"学校托管模型（演示）",kind:"openai-compatible",base_url:"https://models.demo.invalid/v1",models:["school-model-demo"],default_model:"school-model-demo",input_cost_per_million_usd:0.5,output_cost_per_million_usd:1.5,max_output_tokens:4096,enabled:true,secret_configured:true,revision:1,updated_at:now}],model_quotas:[{version:"model-quota-policy.v1",id:"quota-demo-course",course_id:dashboard.course.id,monthly_request_limit:1000,monthly_token_limit:1000000,monthly_cost_limit_usd:50,enabled:true,revision:1,period:"2026-05",used_requests:48,used_tokens:125440,used_cost_usd:3.42,reserved_requests:1,reserved_tokens:4096,reserved_cost_usd:0.01,updated_at:now}] }; }
async function checksum(value:unknown):Promise<string>{const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(value)));return [...new Uint8Array(bytes)].map(item=>item.toString(16).padStart(2,"0")).join("");}

export class LocalStoragePortalRepository implements PortalRepository {
  private cache: DemoState | undefined;

  private load(): DemoState {
    if (this.cache) return this.cache;
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return this.save(initialState());
    try {
      const parsed = JSON.parse(raw) as Partial<DemoState> & {schema_version?:number};
      if(parsed.schema_version&&parsed.schema_version<SCHEMA_VERSION&&parsed.dashboard&&parsed.qa&&parsed.appeals){const migratedScore={...parsed.dashboard.score,snapshot_version:parsed.dashboard.score.snapshot_version??1};parsed.dashboard.score=migratedScore;const defaults=initialState();return this.save({schema_version:SCHEMA_VERSION,signed_in:parsed.signed_in??true,dashboard:parsed.dashboard,qa:parsed.qa,appeals:parsed.appeals,scores:parsed.scores??[migratedScore],provisions:parsed.provisions??[],course_versions:parsed.course_versions??[],enrollment_imports:parsed.enrollment_imports??[],invites:parsed.invites??[],course_groups:parsed.course_groups??defaults.course_groups,designs:parsed.designs??[],retention:parsed.retention??defaults.retention,model_providers:defaults.model_providers,model_quotas:defaults.model_quotas});}
      if (parsed.schema_version !== SCHEMA_VERSION || typeof parsed.signed_in!=="boolean" || !parsed.dashboard || !parsed.qa || !parsed.appeals || !parsed.scores || !parsed.provisions || !parsed.course_versions || !parsed.enrollment_imports || !parsed.invites || !parsed.course_groups || !parsed.designs || !parsed.retention || !parsed.model_providers || !parsed.model_quotas) {
        throw new Error("unsupported demo data version");
      }
      this.cache = parsed as DemoState;
      return this.cache;
    } catch (error) {
      throw new Error(`演示数据已损坏：${error instanceof Error ? error.message : String(error)}。请使用“重置演示”。`);
    }
  }

  private save(state: DemoState): DemoState { this.cache = state; localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); return state; }
  async login(input: LoginInput): Promise<PortalActor> {
    const role = input.username as PortalRole;
    if (!demoActors[role] || input.password !== input.username) throw new Error("演示账号或密码错误");
    const actor=await this.switchDemoRole(role);const state=this.load();state.signed_in=true;this.save(state);return actor;
  }
  async logout() { const state=this.load();state.signed_in=false;this.save(state); }
  async currentActor() { const state=this.load();return state.signed_in?state.dashboard.actor:null; }
  async oidcProviders(){return [];}
  async adminOidcProviders(){return [];}
  async saveOidcProvider(_input:OidcProviderInputV1):Promise<OidcProviderSummaryV1>{throw new Error("Demo 不保存或模拟身份提供方凭据");}
  async modelProviders(){const state=this.load();if(state.dashboard.actor.role!=="admin")throw new Error("administrator access required");return structuredClone(state.model_providers);}
  async saveModelProvider(_raw:ModelProviderInputV1):Promise<ModelProviderSummaryV1>{ModelProviderInputV1Schema.parse(_raw);throw new Error("Demo 不保存或模拟模型 Provider 凭据");}
  async modelQuotas(){const state=this.load();if(state.dashboard.actor.role!=="admin")throw new Error("administrator access required");return structuredClone(state.model_quotas);}
  async saveModelQuota(raw:ModelQuotaPolicyInputV1){const input=ModelQuotaPolicyInputV1Schema.parse(raw);const state=this.load();if(state.dashboard.actor.role!=="admin")throw new Error("administrator access required");const current=state.model_quotas.find(item=>item.course_id===input.course_id&&item.user_id===input.user_id);if(current&&current.revision!==input.expected_revision)throw new Error("演示模型额度已被并发更新");const quota:ModelQuotaPolicyV1={version:"model-quota-policy.v1",id:current?.id??`quota-demo-${Date.now()}`,course_id:input.course_id,...(input.user_id?{user_id:input.user_id}:{}),monthly_request_limit:input.monthly_request_limit,monthly_token_limit:input.monthly_token_limit,monthly_cost_limit_usd:input.monthly_cost_limit_usd,enabled:input.enabled,revision:(current?.revision??0)+1,period:current?.period??new Date().toISOString().slice(0,7),used_requests:current?.used_requests??0,used_tokens:current?.used_tokens??0,used_cost_usd:current?.used_cost_usd??0,reserved_requests:current?.reserved_requests??0,reserved_tokens:current?.reserved_tokens??0,reserved_cost_usd:current?.reserved_cost_usd??0,updated_at:new Date().toISOString()};if(current)state.model_quotas.splice(state.model_quotas.indexOf(current),1,quota);else state.model_quotas.push(quota);this.save(state);return structuredClone(quota);}
  async adminSystemStatus():Promise<AdminSystemStatusV1>{const state=this.load();if(state.dashboard.actor.role!=="admin")throw new Error("administrator access required");return{version:"admin-system-status.v1",checked_at:new Date().toISOString(),overall:"unavailable",services:["postgres","gitea","minio"].map(id=>({id:id as "postgres"|"gitea"|"minio",status:"unavailable" as const,detail:"静态 Demo 没有生产服务连接"})),workers:[],queues:{pipeline_queued:state.dashboard.runs.filter(run=>run.status==="queued").length,pipeline_active:state.dashboard.runs.filter(run=>run.status==="leased"||run.status==="running").length,outbox_pending:0,provisioning_pending:state.provisions.filter(item=>item.status==="queued"||item.status==="provisioning").length}};}
  async retentionPolicy(){const state=this.load();if(state.dashboard.actor.role!=="admin")throw new Error("administrator access required");return structuredClone(state.retention);}
  async updateRetentionPolicy(raw:RetentionPolicyUpdateV1){const input=RetentionPolicyUpdateV1Schema.parse(raw);const state=this.load();if(state.dashboard.actor.role!=="admin")throw new Error("administrator access required");if(input.expected_revision!==state.retention.revision)throw new Error("演示保留策略已被并发更新");state.retention={version:"retention-policy.v1",ordinary_days:input.ordinary_days,records_days:input.records_days,revision:state.retention.revision+1,updated_at:new Date().toISOString()};this.save(state);return structuredClone(state.retention);}
  async switchDemoRole(role: PortalRole) {
    const state = this.load(); state.dashboard.actor = demoActors[role];state.signed_in=true; this.save(state); return state.dashboard.actor;
  }
  async contexts(){const dashboard=this.load().dashboard;return[{version:"portal-context.v1" as const,course:{id:dashboard.course.id,code:dashboard.course.code,name:dashboard.course.name,term:dashboard.course.term},project:{id:dashboard.project.project_id,status:"active" as const,experiment_id:dashboard.project.experiment_id,stage_key:dashboard.project.current_stage.key,stage_name:dashboard.project.current_stage.name}}];}
  async selectContext(projectId:string){if(projectId!==this.load().dashboard.project.project_id)throw new Error("演示项目上下文不存在");}
  async dashboard() {
    const dashboard = structuredClone(this.load().dashboard);
    if (dashboard.actor.role === "student") {
      dashboard.score.adjustments = dashboard.score.adjustments.filter(
        (item) => item.member_id === dashboard.actor.id,
      );
    }
    return dashboard;
  }
  async courseOperations(courseId:string){const state=this.load();assertStaff(state.dashboard.actor);if(courseId!==state.dashboard.course.id)throw new Error("演示课程不存在");const latestRun=state.dashboard.runs[0];const latestDesign=state.designs.toSorted((a,b)=>b.revision-a.revision)[0];return{version:"course-operations.v1" as const,course_id:courseId,generated_at:new Date().toISOString(),projects:[{project_id:state.dashboard.project.project_id,status:"active" as const,stage_key:state.dashboard.project.current_stage.key,stage_name:state.dashboard.project.current_stage.name,member_names:[demoActors.student.display_name,"陈同学"],latest_run_status:latestRun?.status,score_state:state.dashboard.score.state,final_score:state.dashboard.score.final_score,failed_runs:state.dashboard.runs.filter(run=>run.status==="failed").length,open_appeals:state.appeals.filter(item=>item.status!=="closed").length,design_status:latestDesign?.status}]};}
  async setNotificationRead(notificationId:string,read:boolean):Promise<NotificationV1>{const state=this.load();const notification=state.dashboard.notifications.find(item=>item.id===notificationId);if(!notification)throw new Error("演示通知不存在");notification.read=read;this.save(state);return structuredClone(notification);}
  async dryRunCourseManifest(raw:unknown):Promise<CourseManifestDryRunV1>{assertTeacher(this.load().dashboard.actor);const parsed=CourseManifestV1Schema.safeParse(raw);if(!parsed.success)return{version:"course-manifest-dry-run.v1",valid:false,changes:[],issues:parsed.error.issues.map(issue=>({path:issue.path.join("."),message:issue.message}))};const state=this.load();const courseId=parsed.data.course.code===state.dashboard.course.code&&parsed.data.course.term===state.dashboard.course.term?state.dashboard.course.id:undefined;return{version:"course-manifest-dry-run.v1",valid:true,course_id:courseId,next_manifest_version:Math.max(0,...state.course_versions.filter(item=>item.course_id===(courseId??"course-demo-new")).map(item=>item.manifest_version))+1,checksum:await checksum(parsed.data),changes:[courseId?"为现有演示课程创建新草稿":"创建演示课程草稿",`配置 ${parsed.data.stages.length} 个 StageGate`],issues:[]};}
  async importCourseManifest(raw:CourseManifestV1,reason:string){const state=this.load();assertTeacher(state.dashboard.actor);if(reason.trim().length<10)throw new Error("导入理由至少需要 10 个字符");const manifest=CourseManifestV1Schema.parse(raw);const courseId=manifest.course.code===state.dashboard.course.code&&manifest.course.term===state.dashboard.course.term?state.dashboard.course.id:`course-demo-${Date.now()}`;const contentChecksum=await checksum(manifest);if(state.course_versions.some(item=>item.course_id===courseId&&item.checksum===contentChecksum))throw new Error("相同内容的课程清单版本已存在");for(const item of state.course_versions)if(item.course_id===courseId&&item.state==="draft")item.state="superseded";const now=new Date().toISOString();const version:CourseManifestVersionV1={version:"course-manifest-version.v1",course_id:courseId,manifest_version:Math.max(0,...state.course_versions.filter(item=>item.course_id===courseId).map(item=>item.manifest_version))+1,state:"draft",manifest,checksum:contentChecksum,created_at:now};state.course_versions.push(version);this.save(state);return structuredClone(version);}
  async courseManifestVersions(courseId:string){const state=this.load();assertTeacher(state.dashboard.actor);return structuredClone(state.course_versions.filter(item=>item.course_id===courseId).toSorted((a,b)=>b.manifest_version-a.manifest_version));}
  async publishCourseManifest(courseId:string,manifestVersion:number,reason:string){const state=this.load();assertTeacher(state.dashboard.actor);if(reason.trim().length<10)throw new Error("发布理由至少需要 10 个字符");const target=state.course_versions.find(item=>item.course_id===courseId&&item.manifest_version===manifestVersion&&item.state==="draft");if(!target)throw new Error("待发布课程清单版本不存在");for(const item of state.course_versions)if(item.course_id===courseId&&item.state==="published")item.state="superseded";target.state="published";target.published_at=new Date().toISOString();state.dashboard.course={...state.dashboard.course,id:courseId,code:target.manifest.course.code,name:target.manifest.course.name,term:target.manifest.course.term,status:"published"};this.save(state);return structuredClone(target);}
  async rollbackCourseManifest(courseId:string,targetManifestVersion:number,reason:string){const state=this.load();assertTeacher(state.dashboard.actor);if(reason.trim().length<10)throw new Error("回滚理由至少需要 10 个字符");const source=state.course_versions.find(item=>item.course_id===courseId&&item.manifest_version===targetManifestVersion&&item.state==="superseded");if(!source)throw new Error("目标历史版本不存在或不能回滚");for(const item of state.course_versions)if(item.course_id===courseId&&(item.state==="published"||item.state==="draft"))item.state="superseded";const now=new Date().toISOString();const restored:CourseManifestVersionV1={...structuredClone(source),manifest_version:Math.max(...state.course_versions.filter(item=>item.course_id===courseId).map(item=>item.manifest_version))+1,state:"published",rollback_of:targetManifestVersion,created_at:now,published_at:now};state.course_versions.push(restored);this.save(state);return structuredClone(restored);}
  async importEnrollmentCsv(raw:EnrollmentCsvImportV1){const state=this.load();assertTeacher(state.dashboard.actor);const input=EnrollmentCsvImportV1Schema.parse(raw);const parsed=parseEnrollmentCsv(input.csv);const result:EnrollmentImportResultV1={version:"enrollment-import-result.v1",course_id:input.course_id,dry_run:input.dry_run,accepted:parsed.rows.length,created_users:input.dry_run||parsed.issues.length?0:parsed.rows.length,updated_memberships:input.dry_run||parsed.issues.length?0:parsed.rows.length,issues:parsed.issues};if(!input.dry_run&&!parsed.issues.length){state.enrollment_imports.push(result);this.save(state);}return structuredClone(result);}
  async enrollmentInvites(courseId:string):Promise<EnrollmentInviteSummaryV1[]>{const state=this.load();assertTeacher(state.dashboard.actor);if(courseId!==state.dashboard.course.id)throw new Error("演示课程不存在");return structuredClone(state.invites.map(({code:_code,redeemed_user_ids:_users,...invite})=>invite));}
  async createEnrollmentInvite(raw:EnrollmentInviteCreateV1):Promise<EnrollmentInviteIssuedV1>{const input=EnrollmentInviteCreateV1Schema.parse(raw);const state=this.load();assertTeacher(state.dashboard.actor);if(input.course_id!==state.dashboard.course.id)throw new Error("演示课程不存在");const now=new Date();if(new Date(input.expires_at).getTime()-now.getTime()<5*60_000)throw new Error("邀请码有效期至少为 5 分钟");const code=`vosi_demo_${crypto.randomUUID().replaceAll("-","")}`;const invite:DemoInvite={version:"enrollment-invite-summary.v1",id:`invite-demo-${Date.now()}`,course_id:input.course_id,role:input.role,expires_at:input.expires_at,max_uses:input.max_uses,uses:0,revoked:false,created_at:now.toISOString(),code,redeemed_user_ids:[]};state.invites.unshift(invite);this.save(state);const {redeemed_user_ids:_users,...issued}=structuredClone(invite);return{...issued,version:"enrollment-invite-issued.v1"};}
  async redeemEnrollmentInvite(raw:EnrollmentInviteRedeemV1):Promise<EnrollmentInviteRedemptionV1>{const input=EnrollmentInviteRedeemV1Schema.parse(raw);const state=this.load();const invite=state.invites.find(item=>item.code===input.code);if(!invite||invite.revoked||new Date(invite.expires_at).getTime()<=Date.now()||invite.uses>=invite.max_uses)throw new Error("演示邀请码不存在、已失效或已用尽");if(invite.role!==state.dashboard.actor.role)throw new Error("演示邀请码角色与当前账户角色不一致");if(!invite.redeemed_user_ids.includes(state.dashboard.actor.id)){invite.redeemed_user_ids.push(state.dashboard.actor.id);invite.uses+=1;this.save(state);}return{version:"enrollment-invite-redemption.v1",invite_id:invite.id,course_id:invite.course_id,user_id:state.dashboard.actor.id,role:invite.role,redeemed_at:new Date().toISOString()};}
  async courseGroups(courseId:string):Promise<CourseGroupV1[]>{const state=this.load();assertStaff(state.dashboard.actor);if(courseId!==state.dashboard.course.id)throw new Error("演示课程不存在");return structuredClone(state.course_groups);}
  async createCourseGroup(courseId:string,raw:CourseGroupMutationV1):Promise<CourseGroupV1>{const state=this.load();assertTeacher(state.dashboard.actor);const input=CourseGroupMutationV1Schema.parse(raw);if(input.expected_revision!==0)throw new Error("新建分组的 expected_revision 必须为 0");return this.saveDemoGroup(state,courseId,undefined,input);}
  async updateCourseGroup(courseId:string,groupId:string,raw:CourseGroupMutationV1):Promise<CourseGroupV1>{const state=this.load();assertTeacher(state.dashboard.actor);const input=CourseGroupMutationV1Schema.parse(raw);return this.saveDemoGroup(state,courseId,groupId,input);}
  async projectProvisionOptions():Promise<ProjectProvisionOptionsV1>{const state=this.load();assertTeacher(state.dashboard.actor);return{version:"project-provision-options.v1",experiments:[{id:state.dashboard.project.experiment_id,course_id:state.dashboard.project.course_id,title:"xv6 规范驱动内核",spec_version:"xv6-spec-v1.3.0"}],members:[demoActors.student].map(actor=>({id:actor.id,course_id:state.dashboard.project.course_id,username:actor.username,display_name:actor.display_name}))};}
  async createProject(raw:ProjectProvisionRequestV1){const state=this.load();assertTeacher(state.dashboard.actor);const input=ProjectProvisionRequestV1Schema.parse(raw);const existing=state.provisions.find(item=>item.owner===input.owner&&item.repository===input.repository);if(existing)return structuredClone(existing);const now=new Date().toISOString();const status:ProjectProvisionStatusV1={version:"project-provision-status.v1",project_id:`project-demo-${Date.now()}`,status:"queued",owner:input.owner,repository:input.repository,attempts:0,created_at:now,updated_at:now};state.provisions.push(status);this.save(state);return structuredClone(status);}
  async projectProvisioning(projectId:string){const state=this.load();const status=state.provisions.find(item=>item.project_id===projectId);if(!status)throw new Error("演示项目供应记录不存在");if(status.status==="queued"){status.status="provisioning";status.attempts+=1;status.updated_at=new Date().toISOString();}else if(status.status==="provisioning"){status.status=status.repository.includes("fail")?"failed":"active";status.repo_url=status.status==="active"?`https://gitea.demo/${status.owner}/${status.repository}.git`:undefined;status.last_error=status.status==="failed"?"演示供应失败：仓库名称触发失败场景":undefined;status.updated_at=new Date().toISOString();}this.save(state);return structuredClone(status);}
  async retryProjectProvisioning(projectId:string,reason:string){const state=this.load();assertTeacher(state.dashboard.actor);if(reason.trim().length<10)throw new Error("重试理由至少需要 10 个字符");const status=state.provisions.find(item=>item.project_id===projectId);if(!status||status.status!=="failed")throw new Error("只有失败的供应任务可以重试");status.status="queued";status.last_error=undefined;status.updated_at=new Date().toISOString();this.save(state);return structuredClone(status);}
  async designSubmissions(projectId:string){const state=this.load();if(projectId!==state.dashboard.project.project_id)throw new Error("演示项目不存在");return structuredClone(state.designs.toSorted((a,b)=>b.revision-a.revision));}
  async submitDesign(raw:DesignSubmissionInputV1){const input=DesignSubmissionInputV1Schema.parse(raw);const state=this.load();if(input.project_id!==state.dashboard.project.project_id||input.stage_key!==state.dashboard.project.current_stage.key)throw new Error("演示项目不在可提交的当前阶段");const latest=state.designs.filter(item=>item.project_id===input.project_id&&item.stage_key===input.stage_key).toSorted((a,b)=>b.revision-a.revision)[0];if(latest&&latest.status!=="changes_requested")throw new Error("当前设计提交尚未要求修改或已经通过，不能创建新修订");const now=new Date().toISOString();const submission:DesignSubmissionV1={version:"design-submission.v1",id:`design-demo-${Date.now()}`,project_id:input.project_id,stage_key:input.stage_key,commit_sha:input.commit_sha,revision:(latest?.revision??0)+1,title:input.title,summary:input.summary,invariants:input.invariants,interfaces:input.interfaces,evidence_refs:input.evidence_refs,status:"submitted",submitted_by:state.dashboard.actor.id,created_at:now,updated_at:now};state.designs.push(submission);this.save(state);return structuredClone(submission);}
  async reviewDesign(raw:DesignReviewInputV1){const input=DesignReviewInputV1Schema.parse(raw);const state=this.load();assertStaff(state.dashboard.actor);if(input.target_status==="frozen")assertTeacher(state.dashboard.actor);const submission=state.designs.find(item=>item.id===input.submission_id);if(!submission)throw new Error("演示设计提交不存在");const allowed:Record<string,string[]>={submitted:["review","changes_requested"],review:["passed","changes_requested"],passed:["frozen"]};if(!allowed[submission.status]?.includes(input.target_status))throw new Error(`设计提交状态不能从 ${submission.status} 转换到 ${input.target_status}`);submission.status=input.target_status;submission.reviewed_by=state.dashboard.actor.id;submission.review_feedback=input.feedback;submission.updated_at=new Date().toISOString();state.dashboard.notifications.unshift({id:`notification-design-${Date.now()}`,title:"设计提交状态已更新",body:`${submission.title}：${input.feedback}`,read:false,created_at:submission.updated_at});this.save(state);return structuredClone(submission);}
  async evidence(runId: string) {
    const bundle = createEvidence(runId); const actor = this.load().dashboard.actor;
    if (actor.role === "student") bundle.evidence = bundle.evidence.filter((item) => item.visibility === "public" || item.visibility === "student");
    return bundle;
  }
  async triggerPipeline(input: PipelineRequestV1) {
    const request = PipelineRequestV1Schema.parse(input); const state = this.load();
    if (request.scope !== "public") assertStaff(state.dashboard.actor);
    const run = { version: "pipeline-summary.v1" as const, id: `run-demo-${Date.now()}`, project_id: request.project_id, commit_sha: request.commit_sha, stage_key: request.stage_key, status: "queued" as const, passed: 0, total: 20, public_message: "演示运行已进入队列。", created_at: new Date().toISOString(), retry_of: request.retry_of };
    state.dashboard.runs.unshift(run); this.save(state); return run;
  }
  async review(input: ReviewInput) { const state = this.load(); assertStaff(state.dashboard.actor); if (input.reason.trim().length < 10) throw new Error("操作理由至少需要 10 个字符"); }
  async transitionCourse(courseId:string,target:"active"|"grading"|"appeal"|"closed"|"archived",reason:string){const state=this.load();assertTeacher(state.dashboard.actor);if(courseId!==state.dashboard.course.id)throw new Error("演示课程不存在");if(reason.trim().length<10)throw new Error("课程状态变更理由至少需要 10 个字符");applyCourseTransition(state.dashboard.course.status as CourseState,target);state.dashboard.course.status=target;this.save(state);return target;}
  async calculateScore(raw:ScoreCalculationV1){const input=ScoreCalculationV1Schema.parse(raw);const state=this.load();assertTeacher(state.dashboard.actor);if(input.project_id!==state.dashboard.project.project_id)throw new Error("演示项目不存在");const finished=state.dashboard.runs.filter(run=>run.status==="passed"||run.status==="failed");if(!finished.length||finished.every(run=>run.total===0))throw new Error("项目没有可用于评分的已完成运行");const passed=finished.reduce((sum,run)=>sum+run.passed,0);const total=finished.reduce((sum,run)=>sum+run.total,0);const baseline=Math.round(passed/total*10_000)/100;const previous=state.scores.at(-1);const snapshot:ScoreSnapshotV1={version:"score-snapshot.v1",id:`score-${Date.now()}`,project_id:input.project_id,baseline,adjustments:[],final_score:baseline,state:"draft",evidence_refs:finished.map(run=>run.id),snapshot_version:(previous?.snapshot_version??0)+1,previous_snapshot_id:previous?.id,created_at:new Date().toISOString()};state.scores.push(snapshot);state.dashboard.score=snapshot;if(state.dashboard.course.status==="active")state.dashboard.course.status="grading";this.save(state);return structuredClone(snapshot);}
  async updateScore(raw: ScoreAdjustmentInputV1) { const input=ScoreAdjustmentInputV1Schema.parse(raw);const state = this.load(); assertTeacher(state.dashboard.actor);const previous=state.scores.at(-1)!;if(previous.state!=="draft")throw new Error("只有最新的 draft 成绩快照可以调整");if(!state.dashboard.project.member_ids.includes(input.member_id))throw new Error("调整对象不是项目成员");const final=previous.final_score+input.delta;if(final<0||final>100)throw new Error("调整后的成绩必须在 0 到 100 之间");const snapshot:ScoreSnapshotV1={...structuredClone(previous),id:`score-${Date.now()}`,adjustments:[...previous.adjustments,{member_id:input.member_id,delta:input.delta,reason:input.reason,evidence_refs:input.evidence_refs}],final_score:final,evidence_refs:[...new Set([...previous.evidence_refs,...input.evidence_refs])],snapshot_version:previous.snapshot_version+1,previous_snapshot_id:previous.id,created_at:new Date().toISOString()};state.scores.push(snapshot);state.dashboard.score=snapshot;this.save(state); return structuredClone(snapshot); }
  async transitionScore(raw:ScoreTransitionV1){const input=ScoreTransitionV1Schema.parse(raw);const state=this.load();assertTeacher(state.dashboard.actor);const previous=state.scores.at(-1)!;if(previous.id!==input.score_snapshot_id)throw new Error("只能转换项目最新的成绩快照");const expected=input.target_state==="frozen"?"draft":"frozen";if(previous.state!==expected)throw new Error(`成绩状态不能从 ${previous.state} 转换到 ${input.target_state}`);const snapshot:ScoreSnapshotV1={...structuredClone(previous),id:`score-${Date.now()}`,state:input.target_state,snapshot_version:previous.snapshot_version+1,previous_snapshot_id:previous.id,created_at:new Date().toISOString()};state.scores.push(snapshot);state.dashboard.score=snapshot;this.save(state);return structuredClone(snapshot);}
  async submitAppeal(raw: AppealSubmitV1) { const input=AppealSubmitV1Schema.parse(raw);const state = this.load();if(state.dashboard.actor.role!=="student")throw new Error("仅学生可以提交申诉");if(input.project_id!==state.dashboard.project.project_id)throw new Error("演示项目不存在");if(state.dashboard.course.status!=="appeal")throw new Error("课程申诉窗口尚未开放");if(state.dashboard.score.state!=="published")throw new Error("项目没有已发布成绩快照");if(state.appeals.some(item=>item.member_id===state.dashboard.actor.id&&item.status!=="closed"))throw new Error("已有进行中的申诉");const now=new Date().toISOString();const appeal: AppealRecordV1 = { version: "appeal.v1", id: `appeal-${Date.now()}`, project_id: input.project_id, member_id: state.dashboard.actor.id, status: "submitted", statement: input.statement, evidence_refs: input.evidence_refs,score_snapshot_id:state.dashboard.score.id, created_at: now,updated_at:now };state.appeals.push(appeal); this.save(state); return structuredClone(appeal); }
  async transitionAppeal(raw:AppealTransitionV1){const input=AppealTransitionV1Schema.parse(raw);const state=this.load();assertStaff(state.dashboard.actor);const appeal=state.appeals.find(item=>item.id===input.appeal_id);if(!appeal)throw new Error("申诉不存在");const expected=input.target_status==="fact_check"?"submitted":input.target_status==="decision"?"fact_check":"decision";if(appeal.status!==expected)throw new Error(`申诉状态不能从 ${appeal.status} 转换到 ${input.target_status}`);if(input.target_status!=="fact_check")assertTeacher(state.dashboard.actor);if(input.target_status==="decision"){const previous=state.scores.at(-1)!;const final=previous.final_score+(input.score_delta??0);if(final<0||final>100)throw new Error("申诉裁决后的成绩必须在 0 到 100 之间");const snapshot:ScoreSnapshotV1={...structuredClone(previous),id:`score-${Date.now()}`,final_score:final,adjustments:input.score_delta?[...previous.adjustments,{member_id:appeal.member_id,delta:input.score_delta,reason:input.decision!,evidence_refs:[appeal.id]}]:previous.adjustments,evidence_refs:[...new Set([...previous.evidence_refs,appeal.id])],snapshot_version:previous.snapshot_version+1,previous_snapshot_id:previous.id,created_at:new Date().toISOString()};state.scores.push(snapshot);state.dashboard.score=snapshot;appeal.decision=input.decision;appeal.resolved_score_snapshot_id=snapshot.id;}appeal.status=input.target_status;appeal.updated_at=new Date().toISOString();this.save(state);return structuredClone(appeal);}
  async appeals(projectId:string){const state=this.load();if(projectId!==state.dashboard.project.project_id)throw new Error("演示项目不存在");return structuredClone(state.appeals.filter(item=>state.dashboard.actor.role==="student"?item.member_id===state.dashboard.actor.id:true));}
  async ask(input: { content: string; project_id?:string }) {
    const state = this.load(); const now = new Date().toISOString();
    if(input.project_id&&input.project_id!==state.dashboard.project.project_id)throw new Error("演示项目上下文不存在");
    state.qa.messages.push({ id: `q-${Date.now()}`, role: "user", content: input.content, object_refs: [], created_at: now });
    state.qa.messages.push({ id: `a-${Date.now()}`, role: "assistant", content: "建议先对照当前阶段的公开不变量，检查 unmap 后页表项与 TLB 刷新路径。演示模式不会执行代码。", object_refs: ["course-memory-manual"], created_at: now });
    this.save(state); return structuredClone(state.qa);
  }
  async qaThread(threadId:string){const thread=this.load().qa;if(thread.id!==threadId)throw new Error("演示问答线程不存在");return structuredClone(thread);}
  watchQa(threadId:string,_afterCount:number,onThread:(thread:QaThreadV1)=>void,onError:(error:Error)=>void){queueMicrotask(()=>{void this.qaThread(threadId).then(onThread,onError);});return()=>undefined;}
  async agentAudits():Promise<AgentAuditV1[]>{assertStaff(this.load().dashboard.actor);return[{version:"agent-audit.v1",id:"audit-demo-qa",project_id:this.load().dashboard.project.project_id,actor_id:demoActors.student.id,model:"school-model-demo",task_kind:"knowledgebase_qa",risk_level:"low",risk_flags:[],prompt_summary:"询问 unmap 后为何需要刷新 TLB",response_summary:"回答引用公开课程手册，不包含 hidden tests。",created_at:"2026-05-16T09:00:00.000Z"}];}
  async modelCredentials():Promise<ModelCredentialRefV1[]>{return[];}
  async saveModelCredential(_input:ModelCredentialInputV1):Promise<ModelCredentialRefV1>{throw new Error("Demo 不保存或模拟模型密钥");}
  async revokeModelCredential(_credentialId:string,_reason:string):Promise<ModelCredentialRefV1>{throw new Error("Demo 不保存或模拟模型密钥");}
  private saveDemoGroup(state:DemoState,courseId:string,groupId:string|undefined,input:CourseGroupMutationV1):CourseGroupV1{if(courseId!==state.dashboard.course.id)throw new Error("演示课程不存在");if(input.member_ids.some(memberId=>!state.dashboard.project.member_ids.includes(memberId)))throw new Error("分组成员必须是该课程的演示学生");const conflict=state.course_groups.find(group=>group.id!==groupId&&group.member_ids.some(memberId=>input.member_ids.includes(memberId)));if(conflict)throw new Error(`成员已属于分组 ${conflict.name}`);const now=new Date().toISOString();let group:CourseGroupV1;if(groupId){const index=state.course_groups.findIndex(item=>item.id===groupId);if(index<0||state.course_groups[index].revision!==input.expected_revision)throw new Error("分组不存在或已被并发更新");group={...state.course_groups[index],name:input.name,member_ids:[...input.member_ids],revision:input.expected_revision+1,updated_at:now};state.course_groups[index]=group;}else{group={version:"course-group.v1",id:`group-demo-${Date.now()}`,course_id:courseId,name:input.name,member_ids:[...input.member_ids],revision:1,created_at:now,updated_at:now};state.course_groups.push(group);}this.save(state);return structuredClone(group);}
  async resetDemo() { localStorage.removeItem(STORAGE_KEY); this.cache = undefined; this.save(initialState()); }
}
