import type { Sql } from "postgres";
import * as client from "openid-client";
import type { OidcProviderInputV1, OidcProviderSummaryV1, PortalActor } from "vos-core/portal-contracts";
import { OidcProviderInputV1Schema, OidcProviderSummaryV1Schema } from "vos-core/portal-contracts";
import { EnvelopeEncryption } from "../storage/envelope.ts";

type Row=Record<string,unknown>;
type OidcFetch=NonNullable<client.DiscoveryRequestOptions[typeof client.customFetch]>;
async function hash(value:string):Promise<string>{return new Bun.CryptoHasher("sha256").update(value).digest("hex");}
function identifier(prefix:string):string{return `${prefix}-${crypto.randomUUID()}`;}
function bytes(value:unknown):Uint8Array{if(value instanceof Uint8Array)return value;throw new Error("encrypted OIDC value is not binary");}
function claim(claims:Record<string,unknown>,name:string,fallback?:string):string{const value=claims[name];if(typeof value==="string"&&value.trim())return value.trim();if(fallback!==undefined)return fallback;throw new Error(`OIDC claim ${name} is required`);}
export async function consumeOidcAuthorization(sql:Sql,providerId:string,state:string):Promise<Row>{const rows=await sql.begin(async tx=>await tx`update oidc_authorizations set consumed_at=now() where state_hash=${await hash(state)} and provider_id=${providerId} and consumed_at is null and expires_at>now() returning *`);const authorization=rows[0] as Row|undefined;if(!authorization)throw new Error("OIDC state is invalid, expired, or already consumed");return authorization;}

export class OidcService {
  private constructor(private readonly sql:Sql,private readonly envelope:EnvelopeEncryption,private readonly fetchImpl?:OidcFetch){}
  static async create(sql:Sql,masterKey:string,options:{fetch?:OidcFetch}={}):Promise<OidcService>{return new OidcService(sql,await EnvelopeEncryption.fromBase64Url(masterKey),options.fetch);}
  private async discover(provider:Row,secret:string):Promise<client.Configuration>{return client.discovery(new URL(String(provider.issuer)),String(provider.client_id),secret,undefined,this.fetchImpl?{[client.customFetch]:this.fetchImpl}:undefined);}
  async saveProvider(current:PortalActor,raw:OidcProviderInputV1,traceId:string,idempotencyKey:string,requestHash:string):Promise<OidcProviderSummaryV1>{if(current.role!=="admin")throw new Error("admin access required");const input=OidcProviderInputV1Schema.parse(raw);return await this.sql.begin(async tx=>{await tx`select pg_advisory_xact_lock(hashtext(${`${current.id}:${idempotencyKey}`}))`;const existing=await tx`select request_hash,response from idempotency_keys where actor_id=${current.id} and key=${idempotencyKey} and expires_at>now()`;if(existing[0]){if(existing[0].request_hash!==requestHash)throw new Error("幂等键已被不同请求使用");return OidcProviderSummaryV1Schema.parse(existing[0].response);}const sealed=await this.envelope.seal(input.client_secret,`oidc-provider:${input.id}`);const rows=await tx`insert into oidc_providers(id,name,issuer,client_id,client_secret_cipher,client_secret_iv,scopes,username_claim,display_name_claim,role_claim,role_mappings,default_role,enabled) values(${input.id},${input.name},${input.issuer},${input.client_id},${sealed.cipher},${sealed.iv},${input.scopes},${input.username_claim},${input.display_name_claim},${input.role_claim??null},${tx.json(input.role_mappings)},${input.default_role},${input.enabled}) on conflict(id) do update set name=excluded.name,issuer=excluded.issuer,client_id=excluded.client_id,client_secret_cipher=excluded.client_secret_cipher,client_secret_iv=excluded.client_secret_iv,scopes=excluded.scopes,username_claim=excluded.username_claim,display_name_claim=excluded.display_name_claim,role_claim=excluded.role_claim,role_mappings=excluded.role_mappings,default_role=excluded.default_role,enabled=excluded.enabled,version=oidc_providers.version+1,updated_at=now() returning *`;await tx`insert into audit_events(id,actor_id,action,resource_type,resource_id,reason,trace_id,payload) values(${identifier("audit")},${current.id},'oidc.provider.upsert','oidc_provider',${input.id},${input.reason},${traceId},${tx.json({issuer:input.issuer,client_id:input.client_id,enabled:input.enabled})})`;const response=this.summary(rows[0] as Row);await tx`insert into idempotency_keys(actor_id,key,request_hash,status_code,response,expires_at) values(${current.id},${idempotencyKey},${requestHash},200,${tx.json(response)},now()+interval '24 hours')`;return response;});}
  async providers(includeDisabled=false):Promise<OidcProviderSummaryV1[]>{const rows=includeDisabled?await this.sql`select * from oidc_providers order by name`:await this.sql`select * from oidc_providers where enabled=true order by name`;return rows.map(row=>this.summary(row as Row));}
  async start(providerId:string,redirectUri:string,returnTo:string):Promise<URL>{if(!/^\/[a-zA-Z0-9/_-]*$/.test(returnTo))throw new Error("OIDC return_to must be a local absolute path");const rows=await this.sql`select * from oidc_providers where id=${providerId} and enabled=true`;const provider=rows[0] as Row|undefined;if(!provider)throw new Error("OIDC provider is unavailable");const secret=await this.envelope.open(bytes(provider.client_secret_cipher),bytes(provider.client_secret_iv),`oidc-provider:${providerId}`);const config=await this.discover(provider,secret);const codeVerifier=client.randomPKCECodeVerifier();const state=client.randomState();const nonce=client.randomNonce();const flow=await this.envelope.seal(JSON.stringify({code_verifier:codeVerifier,nonce}),`oidc-flow:${providerId}`);const flowId=identifier("oidc-flow");await this.sql.begin(async tx=>{await tx`insert into oidc_authorizations(id,provider_id,state_hash,flow_cipher,flow_iv,return_to,expires_at) values(${flowId},${providerId},${await hash(state)},${flow.cipher},${flow.iv},${returnTo},now()+interval '10 minutes')`;await tx`insert into audit_events(id,actor_id,action,resource_type,resource_id,reason,trace_id,payload) values(${identifier("audit")},null,'auth.oidc.start','oidc_authorization',${flowId},'OIDC authorization code flow initiated',${identifier("trace")},${tx.json({provider_id:providerId,return_to:returnTo})})`;});const codeChallenge=await client.calculatePKCECodeChallenge(codeVerifier);return client.buildAuthorizationUrl(config,{redirect_uri:redirectUri,scope:(provider.scopes as string[]).join(" "),code_challenge:codeChallenge,code_challenge_method:"S256",state,nonce});}
  async callback(providerId:string,currentUrl:URL):Promise<{actor:PortalActor;token:string;csrf:string;return_to:string}>{const state=currentUrl.searchParams.get("state");if(!state)throw new Error("OIDC callback is missing state");const authorization=await consumeOidcAuthorization(this.sql,providerId,state);const providers=await this.sql`select * from oidc_providers where id=${providerId} and enabled=true`;const provider=providers[0] as Row|undefined;if(!provider)throw new Error("OIDC provider is unavailable");const secret=await this.envelope.open(bytes(provider.client_secret_cipher),bytes(provider.client_secret_iv),`oidc-provider:${providerId}`);const flow=JSON.parse(await this.envelope.open(bytes(authorization.flow_cipher),bytes(authorization.flow_iv),`oidc-flow:${providerId}`)) as {code_verifier?:unknown;nonce?:unknown};if(typeof flow.code_verifier!=="string"||typeof flow.nonce!=="string")throw new Error("OIDC flow secret is invalid");const config=await this.discover(provider,secret);const tokens=await client.authorizationCodeGrant(config,currentUrl,{pkceCodeVerifier:flow.code_verifier,expectedState:state,expectedNonce:flow.nonce,idTokenExpected:true});const claims=tokens.claims();if(!claims)throw new Error("OIDC provider returned no ID Token claims");const session=await this.completeLogin(provider,claims as Record<string,unknown>);return{...session,return_to:String(authorization.return_to)};}
  private async completeLogin(provider:Row,claims:Record<string,unknown>):Promise<{actor:PortalActor;token:string;csrf:string}>{const issuer=String(provider.issuer);const subject=claim(claims,"sub");let username=claim(claims,String(provider.username_claim),subject).slice(0,200);const displayName=claim(claims,String(provider.display_name_claim),username).slice(0,200);const mappings=OidcProviderSummaryV1Schema.shape.role_mappings.parse(provider.role_mappings);const externalRole=provider.role_claim?claim(claims,String(provider.role_claim),""):"";const role=mappings[externalRole]??OidcProviderSummaryV1Schema.shape.default_role.parse(provider.default_role);return await this.sql.begin(async tx=>{let users=await tx`select * from users where oidc_issuer=${issuer} and oidc_subject=${subject} for update`;let row=users[0] as Row|undefined;if(!row){const conflict=await tx`select 1 from users where lower(username)=lower(${username}) and deleted_at is null`;if(conflict.length)username=`${username.slice(0,180)}-${(await hash(`${issuer}:${subject}`)).slice(0,8)}`;users=await tx`insert into users(id,username,display_name,role,oidc_issuer,oidc_subject,status) values(${identifier("user")},${username},${displayName},${role},${issuer},${subject},'active') returning *`;row=users[0] as Row;}else{const updated=await tx`update users set display_name=${displayName},role=${role},status='active',version=version+1,updated_at=now() where id=${String(row.id)} returning *`;row=updated[0] as Row;}const token=crypto.randomUUID()+crypto.randomUUID();const csrf=crypto.randomUUID();await tx`insert into sessions(id,user_id,token_hash,csrf_hash,expires_at,token_kind,scopes) values(${identifier("session")},${String(row.id)},${await hash(token)},${await hash(csrf)},now()+interval '12 hours','web',${tx.json([])})`;await tx`insert into audit_events(id,actor_id,action,resource_type,resource_id,reason,trace_id,payload) values(${identifier("audit")},${String(row.id)},'auth.oidc.login','user',${String(row.id)},'OIDC authorization code login',${`trace-${crypto.randomUUID()}`},${tx.json({issuer,subject,provider_id:String(provider.id)})})`;return{actor:{id:String(row.id),username:String(row.username),display_name:String(row.display_name),role},token,csrf};});}
  private summary(row:Row):OidcProviderSummaryV1{return OidcProviderSummaryV1Schema.parse({version:"oidc-provider-summary.v1",id:String(row.id),name:String(row.name),issuer:String(row.issuer),client_id:String(row.client_id),scopes:row.scopes,username_claim:String(row.username_claim),display_name_claim:String(row.display_name_claim),role_claim:row.role_claim?String(row.role_claim):undefined,role_mappings:row.role_mappings,default_role:row.default_role,enabled:Boolean(row.enabled),secret_configured:true,updated_at:new Date(String(row.updated_at)).toISOString()});}
}
