import { db } from "../storage/database.ts";

export async function seed():Promise<void>{
  if(process.env.NODE_ENV==="production"&&process.env.VOS_PORTAL_ALLOW_SEED!=="1")throw new Error("Production seed requires VOS_PORTAL_ALLOW_SEED=1");
  const sql=db();const password=await Bun.password.hash("student",{algorithm:"argon2id",memoryCost:65536,timeCost:3});const staffPassword=await Bun.password.hash("teacher",{algorithm:"argon2id",memoryCost:65536,timeCost:3});
  await sql.begin(async(tx)=>{
    for(const user of [{id:"user-student",username:"student",name:"李明同学",role:"student",hash:password},{id:"user-ta",username:"ta",name:"张助教",role:"ta",hash:await Bun.password.hash("ta",{algorithm:"argon2id"})},{id:"user-teacher",username:"teacher",name:"王老师",role:"teacher",hash:staffPassword},{id:"user-admin",username:"admin",name:"系统管理员",role:"admin",hash:await Bun.password.hash("admin",{algorithm:"argon2id"})}])await tx`insert into users(id,username,password_hash,display_name,role) values(${user.id},${user.username},${user.hash},${user.name},${user.role}) on conflict(id) do update set password_hash=excluded.password_hash,display_name=excluded.display_name,role=excluded.role,updated_at=now()`;
    await tx`insert into courses(id,code,name,term,status) values('course-os-2026','OS-LAB','操作系统设计实验','2026 春','active') on conflict(id) do nothing`;
    await tx`insert into course_memberships(course_id,user_id,role,status,source) values('course-os-2026','user-teacher','teacher','active','manual'),('course-os-2026','user-ta','ta','active','manual'),('course-os-2026','user-student','student','active','manual') on conflict(course_id,user_id) do update set role=excluded.role,status='active'`;
    await tx`insert into experiments(id,course_id,title,spec_version,publish_state,base_repo_url) values('experiment-xv6','course-os-2026','xv6 规范驱动内核','xv6-spec-v1.3.0','published','http://gitea:3000/templates/xv6-spec.git') on conflict(id) do nothing`;
    const names=["架构种子","启动","内存管理","中断","用户态","文件系统","综合评测"];const keys=["seed","boot","memory","interrupts","user","fs","final"];
    for(let sequence=0;sequence<names.length;sequence++){const status=sequence<2?"passed":sequence===2?"review":"locked";await tx`insert into stage_gates(id,experiment_id,key,name,sequence,status,config) values(${`stage-${sequence}`},'experiment-xv6',${keys[sequence]},${names[sequence]},${sequence},${status},${tx.json({required_artifacts:["design","implementation"],required_evidence:[{suite:"public",case_name:"stage-gate",required_result:"pass"}],required_review_artifacts:[],manual_review_required:sequence===2||sequence===6})}) on conflict(id) do update set status=excluded.status,config=excluded.config`;}
    await tx`insert into projects(id,experiment_id,current_stage_id,repo_url,status,policy_snapshot_ref) values('project-xv6-group-3','experiment-xv6','stage-2','http://gitea:3000/os/xv6-group-3.git','active','policy-v1.3.0') on conflict(id) do nothing`;
    await tx`insert into project_members(project_id,user_id) values('project-xv6-group-3','user-student') on conflict do nothing`;
    await tx`insert into pipeline_runs(id,project_id,commit_sha,stage_key,scope,status,passed,total,failure_class,public_message,policy_snapshot_ref,requested_by,reason,created_at,finished_at) values('run-20260516-a1b2c3d','project-xv6-group-3','a1b2c3d','memory','public','failed',18,20,'verification_failure','页表解除映射行为与公开规范不一致。','policy-v1.3.0','user-student','seeded classroom evidence','2026-05-16T14:32:10Z','2026-05-16T14:56:48Z') on conflict(id) do nothing`;
    await tx`insert into evidence_records(id,run_id,suite,case_name,result,visibility,metrics,public_message) values('ev-unmap','run-20260516-a1b2c3d','page-table','pt-unmap','fail','student',${tx.json({ticks:1420000,exit_code:0})},'访问未触发页异常，返回旧映射数据。') on conflict(id) do nothing`;
    await tx`insert into object_refs(id,project_id,run_id,uri,object_key,sha256,size_bytes,content_type,visibility,label,upload_status) values('artifact-serial','project-xv6-group-3','run-20260516-a1b2c3d','s3://vos-artifacts/run-20260516-a1b2c3d/serial.log','run-20260516-a1b2c3d/serial.log',${"0".repeat(64)},12984,'text/plain','student','QEMU 串行日志','pending') on conflict(id) do nothing`;
    await tx`insert into score_snapshots(id,project_id,snapshot_version,baseline,final_score,state,evidence_refs,created_by,transition_reason) values('score-draft','project-xv6-group-3',1,28,28,'draft',${tx.json(["run-20260516-a1b2c3d"])},'user-teacher','seeded classroom score snapshot') on conflict(id) do nothing`;
    await tx`insert into notifications(id,user_id,title,body) values('notice-review','user-student','评审已完成','TA-07 已完成阶段 2 的评审。') on conflict(id) do nothing`;
  });console.log("seeded VOS Portal classroom data");
}
