import { describe, expect, test } from "bun:test";
import { AssessmentSubmissionRequestV1Schema, CourseManifestV1Schema, CourseOperationsV2Schema, DesignSubmissionInputV1Schema, EnrollmentInviteCreateV1Schema, EnrollmentInviteRedeemV1Schema, ModelProviderInputV1Schema, ModelQuotaPolicyInputV1Schema, ObjectUploadRequestV1Schema, OAuthProviderInputV1Schema, OidcProviderInputV1Schema, PipelineRequestV1Schema, ProjectProvisionRequestV1Schema, ReviewActionV1Schema, ServiceTokenCreateV1Schema, portalOpenApiDocument } from "vos-core/portal-contracts";
import { transitionCourse, transitionProject } from "../domain/state-machines.ts";

describe("portal contracts and state machines", () => {
  test("publishes the administrator and notification contracts",()=>{const document=portalOpenApiDocument() as {paths:Record<string,unknown>;components:{schemas:Record<string,unknown>}};expect(document.paths["/api/v1/admin/system/status"]).toBeTruthy();expect(document.paths["/api/v1/admin/retention"]).toBeTruthy();expect(document.paths["/api/v1/courses/{course_id}/operations"]).toBeTruthy();expect(document.paths["/api/v1/notifications/{notification_id}"]).toBeTruthy();expect(document.components.schemas.AdminSystemStatusV1).toBeTruthy();expect(document.components.schemas.RetentionPolicyV1).toBeTruthy();expect(document.components.schemas.CourseOperationsV2).toBeTruthy();expect(document.components.schemas.NotificationV1).toBeTruthy();expect(document.components.schemas.NotificationReadV1).toBeTruthy();});
  test("requires the structured CourseOperationsV2 latest-run projection",()=>{const value={version:"course-operations.v2" as const,course_id:"course-1",generated_at:new Date().toISOString(),projects:[{project_id:"project-1",status:"active" as const,stage_key:"memory",stage_name:"Memory",member_names:["Student"],latest_run:{id:"run-1",status:"failed" as const,stage_key:"memory",created_at:new Date().toISOString(),passed:18,total:20,failure_class:"verification_failure",public_message:"Public failure"},failed_runs:1,open_appeals:0}]};expect(CourseOperationsV2Schema.parse(value).projects[0].latest_run?.total).toBe(20);expect(CourseOperationsV2Schema.safeParse({...value,projects:[{...value.projects[0],latest_run_status:"failed"}]}).success).toBe(false);});
  test("publishes bounded service-token contracts without secret list responses",()=>{const document=portalOpenApiDocument() as {paths:Record<string,unknown>;components:{schemas:Record<string,unknown>}};expect(document.paths["/api/v1/auth/service-tokens"]).toBeTruthy();expect(document.paths["/api/v1/auth/service-tokens/{token_id}/revoke"]).toBeTruthy();expect(document.components.schemas.ServiceTokenIssuedV1).toBeTruthy();expect(ServiceTokenCreateV1Schema.parse({name:"course automation",scopes:["project:read","pipeline:write"],expires_in_minutes:30,reason:"issue bounded course automation token"}).expires_in_minutes).toBe(30);expect(ServiceTokenCreateV1Schema.safeParse({name:"bad",scopes:["admin:*"],expires_in_minutes:10000,reason:"invalid automation token request"}).success).toBe(false);});
  test("publishes bounded role-specific enrollment invites",()=>{const create={course_id:"course-1",role:"student" as const,expires_at:new Date(Date.now()+86_400_000).toISOString(),max_uses:20,reason:"invite the next student cohort"};expect(EnrollmentInviteCreateV1Schema.parse(create).max_uses).toBe(20);expect(EnrollmentInviteCreateV1Schema.safeParse({...create,role:"teacher"}).success).toBe(false);expect(EnrollmentInviteRedeemV1Schema.parse({code:"vosi_abcdefghijklmnopqrstuvwxyz",reason:"join the assigned operating systems course"}).code).toStartWith("vosi_");const document=portalOpenApiDocument() as {paths:Record<string,unknown>;components:{schemas:Record<string,unknown>}};expect(document.paths["/api/v1/enrollment/invites"]).toBeTruthy();expect(document.paths["/api/v1/enrollment/invites/redeem"]).toBeTruthy();expect(document.components.schemas.EnrollmentInviteIssuedV1).toBeTruthy();});
  test("binds authoritative submissions to immutable project inputs",()=>{const input={version:"assessment-submission-request.v1",project_id:"project-1",commit_sha:"a".repeat(40),stage_key:"memory",spec_hash:"b".repeat(64),config_hash:"c".repeat(64),manifest_hash:"d".repeat(64),reason:"submit current clean commit for authoritative assessment"};expect(AssessmentSubmissionRequestV1Schema.parse(input).stage_key).toBe("memory");expect(AssessmentSubmissionRequestV1Schema.safeParse({...input,manifest_hash:"dirty"}).success).toBe(false);const document=portalOpenApiDocument() as {paths:Record<string,unknown>;components:{schemas:Record<string,unknown>}};expect(document.paths["/api/v1/submissions"]).toBeTruthy();expect(document.paths["/api/v1/submissions/{submission_id}"]).toBeTruthy();expect(document.components.schemas.AssessmentSubmissionV1).toBeTruthy();});
  test("generates OpenAPI metadata from the same contract registry",()=>{const document=portalOpenApiDocument() as {openapi:string;paths:Record<string,unknown>;components:{schemas:Record<string,unknown>;securitySchemes:Record<string,unknown>}};expect(document.openapi).toBe("3.1.0");for(const path of ["/api/v1/auth/login","/api/v1/auth/device/code","/api/v1/auth/device/token","/api/v1/auth/device/approve","/api/v1/auth/logout","/api/v1/auth/revoke","/api/v1/contexts","/api/v1/dashboard","/api/v1/internal/gitea/webhook","/api/v1/internal/worker/lease","/api/v1/internal/worker/heartbeat","/api/v1/internal/worker/runs/{run_id}/start","/api/v1/internal/worker/runs/{run_id}/evidence","/api/v1/internal/worker/runs/{run_id}/complete","/api/v1/courses/{course_id}/groups","/api/v1/courses/{course_id}/groups/{group_id}","/api/v1/pipelines","/api/v1/pipelines/{run_id}/cancel","/api/v1/pipelines/{run_id}/reproduction","/api/v1/projects/{project_id}/objects/uploads","/api/v1/auth/oidc/{provider_id}/callback","/api/v1/auth/oauth/{provider_id}/callback","/api/v1/admin/oauth/providers","/api/v1/reviews","/api/v1/grades/transition","/api/v1/appeals/{appeal_id}/transition","/api/v1/ai/qa/{thread_id}/events","/api/v1/ai/credentials","/api/v1/ai/credentials/{credential_id}/revoke"])expect(document.paths[path]).toBeTruthy();expect(document.components.securitySchemes.giteaWebhook).toBeTruthy();expect(document.components.securitySchemes.workerBearer).toBeTruthy();expect(document.components.schemas.PortalContextV1).toBeTruthy();expect(document.components.schemas.CourseGroupV1).toBeTruthy();expect(document.components.schemas.CourseGroupMutationV1).toBeTruthy();expect(document.components.schemas.PipelineRequestV1).toBeTruthy();expect(document.components.schemas.WorkerPipelineLeaseV1).toBeTruthy();expect(document.components.schemas.WorkerEvidenceReportV1).toBeTruthy();expect(document.components.schemas.ObjectUploadRequestV1).toBeTruthy();expect(document.components.schemas.OidcProviderInputV1).toBeTruthy();expect(document.components.schemas.OAuthProviderInputV1).toBeTruthy();expect(document.components.schemas.ReviewActionV1).toBeTruthy();expect(document.components.schemas.ModelCredentialInputV1).toBeTruthy();});
  test("requires auditable review actions",()=>{expect(ReviewActionV1Schema.parse({run_id:"run-1",action:"rerun",reason:"approve a controlled rerun"}).action).toBe("rerun");expect(()=>ReviewActionV1Schema.parse({run_id:"run-1",action:"rerun",reason:"short"})).toThrow();});
  test("validates school model providers and monthly quota policies",()=>{const provider={version:"model-provider-input.v1",id:"school",name:"School model",kind:"openai-compatible",base_url:"https://models.example.edu/v1",models:["school-model"],default_model:"school-model",secret:"secret-at-least-sixteen",input_cost_per_million_usd:1,output_cost_per_million_usd:2,max_output_tokens:4096,enabled:true,expected_revision:0,reason:"configure school model provider"};expect(ModelProviderInputV1Schema.parse(provider).default_model).toBe("school-model");expect(ModelProviderInputV1Schema.safeParse({...provider,base_url:"http://public.example/v1"}).success).toBe(false);expect(ModelProviderInputV1Schema.safeParse({...provider,default_model:"other"}).success).toBe(false);expect(ModelQuotaPolicyInputV1Schema.parse({version:"model-quota-policy-input.v1",course_id:"course-1",monthly_request_limit:100,monthly_token_limit:100000,monthly_cost_limit_usd:25,enabled:true,expected_revision:0,reason:"configure monthly course quota"}).monthly_request_limit).toBe(100);});
  test("binds structured design submissions to immutable commits",()=>{const input={version:"design-submission-input.v1",project_id:"project-1",stage_key:"memory",commit_sha:"a".repeat(40),title:"Memory design",summary:"A reviewable summary of the memory subsystem design.",invariants:["Freed pages are unreachable before reuse."],interfaces:[{name:"vm_unmap",contract:"Removes mappings before returning to the caller."}],evidence_refs:["run-1"],reason:"submit design for stage review"};expect(DesignSubmissionInputV1Schema.parse(input).commit_sha).toBe(input.commit_sha);expect(()=>DesignSubmissionInputV1Schema.parse({...input,commit_sha:"dirty"})).toThrow();});
  test("requires HTTPS OIDC issuers and forbids administrator role mapping",()=>{const base={version:"oidc-provider-input.v1",id:"campus",name:"Campus",issuer:"https://id.example.edu",client_id:"portal",client_secret:"secret",scopes:["openid"],username_claim:"preferred_username",display_name_claim:"name",role_claim:"role",role_mappings:{faculty:"teacher"},default_role:"student",enabled:true,reason:"configure campus provider"};expect(OidcProviderInputV1Schema.parse(base).issuer).toBe(base.issuer);expect(OidcProviderInputV1Schema.safeParse({...base,issuer:"http://id.example.edu"}).success).toBe(false);expect(OidcProviderInputV1Schema.safeParse({...base,role_mappings:{ops:"admin"}}).success).toBe(false);});
  test("requires HTTPS OAuth endpoints and a bounded identity mapping",()=>{const base={version:"oauth-provider-input.v1",id:"campus-oauth",name:"Campus OAuth",issuer:"https://id.example.edu",authorization_endpoint:"https://id.example.edu/authorize",token_endpoint:"https://id.example.edu/token",userinfo_endpoint:"https://id.example.edu/userinfo",client_id:"portal",client_secret:"secret",scopes:["profile"],subject_claim:"id",username_claim:"username",display_name_claim:"name",role_claim:"role",role_mappings:{faculty:"teacher"},default_role:"student",enabled:true,reason:"configure campus oauth provider"};expect(OAuthProviderInputV1Schema.parse(base).userinfo_endpoint).toBe(base.userinfo_endpoint);expect(OAuthProviderInputV1Schema.safeParse({...base,token_endpoint:"http://id.example.edu/token"}).success).toBe(false);expect(OAuthProviderInputV1Schema.safeParse({...base,role_mappings:{ops:"admin"}}).success).toBe(false);});
  test("validates object upload metadata before creating a signed URL",()=>{expect(ObjectUploadRequestV1Schema.parse({sha256:"a".repeat(64),size_bytes:42,content_type:"application/json",visibility:"student",label:"evidence",lineage:{source:"runner"}}).size_bytes).toBe(42);expect(()=>ObjectUploadRequestV1Schema.parse({sha256:"bad",size_bytes:-1,content_type:"application/json\r\nx: y",visibility:"system",label:"",lineage:{}})).toThrow();});
  test("requires private auditable project provisioning requests",()=>{const request={version:"project-provision-request.v1",experiment_id:"experiment-xv6",member_ids:["student-1"],owner:"os-2026",repository:"team-1",template_owner:"templates",template_repository:"xv6",description:"Team repository",private:true,reason:"teacher creates team repository"};expect(ProjectProvisionRequestV1Schema.parse(request).private).toBe(true);expect(()=>ProjectProvisionRequestV1Schema.parse({...request,private:false})).toThrow();});
  test("accepts a versioned course manifest and rejects unknown fields", () => {
    const manifest = { version: "course-manifest.v1", course: { code: "OS", name: "OS Lab", term: "2026" }, experiment: { id: "xv6", title: "xv6", spec_version: "v1" }, stages: [], rubric: [], ai_policy: { allowed_models: [], monthly_budget: 0, allow_byok: true } };
    expect(CourseManifestV1Schema.parse(manifest).version).toBe("course-manifest.v1");
    expect(() => CourseManifestV1Schema.parse({ ...manifest, ignored: true })).toThrow();
  });
  test("keeps candidate stages behind hardware and human gates",()=>{const manifestFor=(stage:object)=>({version:"course-manifest.v1",course:{code:"OS",name:"OS",term:"2026"},experiment:{id:"xv6",title:"xv6",spec_version:"v2"},stages:[stage],rubric:[{id:"hardware",name:"Hardware",weight:100}],ai_policy:{allowed_models:[],monthly_budget:0,allow_byok:false}});const stage={id:"lab9",key:"lab9",name:"Candidate",sequence:8,source_ref:"course/lab9-candidate",spec_refs:["kernel.driver"],test_sets:["lab9.public"],rubric_ids:["hardware"],hardware_gate:"visionfive2-four-hart",human_review_required:true,required_artifacts:[],required_evidence:[],required_review_artifacts:["hardware-report"],manual_review_required:true};expect(CourseManifestV1Schema.parse(manifestFor(stage)).stages[0].source_ref).toBe("course/lab9-candidate");expect(()=>CourseManifestV1Schema.parse(manifestFor({...stage,hardware_gate:"none"}))).toThrow("candidate stages require a hardware gate");expect(()=>CourseManifestV1Schema.parse(manifestFor({...stage,manual_review_required:false}))).toThrow("candidate stages require a hardware gate");expect(()=>CourseManifestV1Schema.parse(manifestFor({...stage,required_review_artifacts:undefined}))).toThrow();expect(()=>CourseManifestV1Schema.parse(manifestFor({...stage,source_ref:"course/lab9-wip"}))).toThrow();});
  test("requires immutable commit identifiers and auditable run reasons", () => {
    expect(() => PipelineRequestV1Schema.parse({ version: "pipeline-request.v1", project_id: "p", commit_sha: "dirty", stage_key: "memory", scope: "public", reason: "short" })).toThrow();
  });
  test("rejects state-machine skips", () => {
    expect(transitionCourse("draft", "published")).toBe("published");
    expect(() => transitionCourse("draft", "active")).toThrow("invalid course transition");
    expect(transitionProject("active", "frozen")).toBe("frozen");
  });
});
