import { beforeEach, describe, expect, test } from "bun:test";
import { LocalStoragePortalRepository } from "../demo/local-storage-repository.ts";

class MemoryStorage implements Storage {
  private data = new Map<string,string>(); get length(){return this.data.size;} clear(){this.data.clear();} getItem(key:string){return this.data.get(key)??null;} key(index:number){return [...this.data.keys()][index]??null;} removeItem(key:string){this.data.delete(key);} setItem(key:string,value:string){this.data.set(key,value);}
}
beforeEach(() => { Object.defineProperty(globalThis, "localStorage", { value: new MemoryStorage(), configurable: true }); });

describe("localStorage demo adapter", () => {
  test("persists notification acknowledgements",async()=>{const repository=new LocalStoragePortalRepository();const before=await repository.dashboard();const unread=before.notifications.find(item=>!item.read);expect(unread).toBeTruthy();await repository.setNotificationRead(unread!.id,true);const after=await new LocalStoragePortalRepository().dashboard();expect(after.notifications.find(item=>item.id===unread!.id)?.read).toBe(true);});
  test("projects class-level teaching operations only to staff",async()=>{const repository=new LocalStoragePortalRepository();const dashboard=await repository.dashboard();await expect(repository.courseOperations(dashboard.course.id)).rejects.toThrow("staff access required");await repository.switchDemoRole("ta");const operations=await repository.courseOperations(dashboard.course.id);expect(operations.version).toBe("course-operations.v2");expect(operations.projects[0].failed_runs).toBe(2);expect(operations.projects[0].latest_run?.id).toBe("run-20260516-a1b2c3d");expect(operations.projects[0].latest_run?.passed).toBe(18);expect(operations.projects[0].design_status).toBe("submitted");});
  test("labels production services unavailable instead of simulating health",async()=>{const repository=new LocalStoragePortalRepository();await repository.switchDemoRole("admin");const status=await repository.adminSystemStatus();expect(status.overall).toBe("unavailable");expect(status.services.every(service=>service.status==="unavailable")).toBe(true);});
  test("persists role and run actions without network", async () => {
    const repository = new LocalStoragePortalRepository();
    await repository.switchDemoRole("ta");
    const before = await repository.dashboard();
    const run = await repository.triggerPipeline({ version: "pipeline-request.v1", project_id: before.project.project_id, commit_sha: "a".repeat(40), stage_key: "memory", scope: "public", retry_of: before.runs[0].id, reason: "助教批准演示公开验证补跑" });
    expect(run.status).toBe("queued");
    expect((await new LocalStoragePortalRepository().dashboard()).runs[0].id).toBe(run.id);
  });
  test("persists role-bound enrollment invite actions",async()=>{const repository=new LocalStoragePortalRepository();await repository.switchDemoRole("teacher");const courseId=(await repository.dashboard()).course.id;const issued=await repository.createEnrollmentInvite({course_id:courseId,role:"student",expires_at:new Date(Date.now()+86_400_000).toISOString(),max_uses:2,reason:"create a demo student enrollment invite"});expect(issued.code).toStartWith("vosi_demo_");expect((await repository.enrollmentInvites(courseId))[0].uses).toBe(0);await repository.switchDemoRole("student");expect((await repository.redeemEnrollmentInvite({code:issued.code,reason:"join the demo course with assigned role"})).role).toBe("student");await repository.switchDemoRole("teacher");expect((await new LocalStoragePortalRepository().enrollmentInvites(courseId))[0].uses).toBe(1);});
  test("redacts staff evidence for students", async () => {
    const repository = new LocalStoragePortalRepository();
    const bundle = await repository.evidence("run-20260516-a1b2c3d");
    expect(bundle.evidence.every((item) => item.visibility !== "staff")).toBe(true);
  });
  test("projects individual score adjustments to the current student", async () => {
    const repository = new LocalStoragePortalRepository();
    await repository.dashboard();
    const state = JSON.parse(localStorage.getItem("vos-portal.demo.v1")!);
    state.dashboard.score.adjustments.push({member_id:"another-student",delta:-4,reason:"private adjustment for another member",evidence_refs:["run-1"]});
    localStorage.setItem("vos-portal.demo.v1",JSON.stringify(state));
    const projected = await new LocalStoragePortalRepository().dashboard();
    expect(projected.score.adjustments.every((item) => item.member_id === projected.actor.id)).toBe(true);
  });
  test("reports corrupted storage instead of silently resetting", async () => {
    localStorage.setItem("vos-portal.demo.v1", "not-json");
    await expect(new LocalStoragePortalRepository().dashboard()).rejects.toThrow("演示数据已损坏");
  });
  test("migrates schema v1 and persists logout",async()=>{const seed=new LocalStoragePortalRepository();const dashboard=await seed.dashboard();localStorage.setItem("vos-portal.demo.v1",JSON.stringify({schema_version:1,dashboard,qa:{version:"qa-thread.v1",id:"qa-1",project_id:dashboard.project.project_id,stage_key:"memory",messages:[]},appeals:[]}));const migrated=new LocalStoragePortalRepository();expect((await migrated.currentActor())?.role).toBe("student");await migrated.logout();expect(await new LocalStoragePortalRepository().currentActor()).toBeNull();expect(JSON.parse(localStorage.getItem("vos-portal.demo.v1")!).schema_version).toBe(11);});
  test("migrates v10 stage projections and fills newly required fields",async()=>{const seed=new LocalStoragePortalRepository();const dashboard=await seed.dashboard();const state=JSON.parse(localStorage.getItem("vos-portal.demo.v1")!);state.schema_version=10;state.dashboard.stages=state.dashboard.stages.map(({status: _status,...stage}:{status?:string;[key:string]:unknown})=>stage);state.dashboard.project.current_stage=(({status: _status,...stage}:{status?:string;[key:string]:unknown})=>stage)(state.dashboard.project.current_stage);state.dashboard.runs=state.dashboard.runs.map(({public_message: _message,...run}:{public_message?:string;[key:string]:unknown})=>run);delete state.model_providers;delete state.model_quotas;localStorage.setItem("vos-portal.demo.v1",JSON.stringify(state));const migrated=new LocalStoragePortalRepository();const loaded=await migrated.dashboard();expect(loaded.stages.find(item=>item.key===dashboard.project.current_stage.key)?.status).toBe("review");expect(loaded.runs[0].public_message).toContain("历史运行");expect(JSON.parse(localStorage.getItem("vos-portal.demo.v1")!).schema_version).toBe(11);expect(JSON.parse(localStorage.getItem("vos-portal.demo.v1")!).model_providers).toHaveLength(1);});
  test("persists audited course-group revisions and rejects stale updates",async()=>{const repository=new LocalStoragePortalRepository();await repository.switchDemoRole("teacher");const dashboard=await repository.dashboard();const current=(await repository.courseGroups(dashboard.course.id))[0];const updated=await repository.updateCourseGroup(dashboard.course.id,current.id,{name:"第 03 组（修订）",member_ids:current.member_ids,expected_revision:current.revision,reason:"adjust the demo teaching group"});expect(updated.revision).toBe(current.revision+1);expect((await new LocalStoragePortalRepository().courseGroups(dashboard.course.id))[0].name).toBe("第 03 组（修订）");await expect(repository.updateCourseGroup(dashboard.course.id,current.id,{name:"stale",member_ids:current.member_ids,expected_revision:current.revision,reason:"attempt stale group update"})).rejects.toThrow("并发更新");await expect(repository.createCourseGroup(dashboard.course.id,{name:"冲突小组",member_ids:current.member_ids,expected_revision:0,reason:"attempt duplicate group membership"})).rejects.toThrow("已属于分组");});
  test("persists administrator retention policy revisions",async()=>{const repository=new LocalStoragePortalRepository();await repository.switchDemoRole("admin");const current=await repository.retentionPolicy();const updated=await repository.updateRetentionPolicy({ordinary_days:45,records_days:400,expected_revision:current.revision,reason:"update demo retention policy"});expect(updated.revision).toBe(current.revision+1);expect((await new LocalStoragePortalRepository().retentionPolicy()).ordinary_days).toBe(45);});
  test("supports the audited design review and resubmission flow",async()=>{const repository=new LocalStoragePortalRepository();const dashboard=await repository.dashboard();await repository.switchDemoRole("ta");const submitted=(await repository.designSubmissions(dashboard.project.project_id))[0];expect((await repository.reviewDesign({version:"design-review-input.v1",submission_id:submitted.id,target_status:"changes_requested",feedback:"请补充跨核完成确认与物理页释放之间的不变量。",reason:"request a traceable design revision"})).status).toBe("changes_requested");await repository.switchDemoRole("student");const revised=await repository.submitDesign({version:"design-submission-input.v1",project_id:dashboard.project.project_id,stage_key:dashboard.project.current_stage.key,commit_sha:"b".repeat(40),title:"TLB 一致性设计修订",summary:"补充跨核完成确认、页表写入可见性和释放物理页之间的严格先后关系。",invariants:["释放物理页前必须收到所有相关 hart 的完成确认。"],interfaces:[{name:"vm_unmap",contract:"返回前完成所有相关 hart 的 TLB 失效确认。"}],evidence_refs:[dashboard.runs[0].id],reason:"submit the requested design revision"});expect(revised.revision).toBe(2);expect((await new LocalStoragePortalRepository().designSubmissions(dashboard.project.project_id))[0].id).toBe(revised.id);});
  test("simulates project provisioning in Demo",async()=>{const repository=new LocalStoragePortalRepository();await repository.switchDemoRole("teacher");const options=await repository.projectProvisionOptions();const created=await repository.createProject({version:"project-provision-request.v1",experiment_id:options.experiments[0].id,member_ids:[options.members[0].id],owner:"demo-course",repository:"team-1",template_owner:"templates",template_repository:"xv6",description:"Demo team",private:true,reason:"teacher creates demo team project"});expect(created.status).toBe("queued");expect((await repository.projectProvisioning(created.project_id)).status).toBe("provisioning");expect((await repository.projectProvisioning(created.project_id)).status).toBe("active");});
  test("persists course publication, rollback and enrollment actions",async()=>{const repository=new LocalStoragePortalRepository();await repository.switchDemoRole("teacher");const dashboard=await repository.dashboard();const manifest={version:"course-manifest.v1" as const,course:{code:dashboard.course.code,name:dashboard.course.name,term:dashboard.course.term},experiment:{id:"demo-lab",title:"Demo Lab",spec_version:"v1"},stages:[{id:"boot",key:"boot",name:"Boot",sequence:0,source_ref:"course/lab1-complete" as const,spec_refs:["kernel.boot"],test_sets:["boot.public"],rubric_ids:["correctness"],hardware_gate:"none" as const,human_review_required:false,required_artifacts:[],required_evidence:[],required_review_artifacts:[],manual_review_required:false}],rubric:[{id:"correctness",name:"Correctness",weight:100}],ai_policy:{allowed_models:["school-default"],monthly_budget:50,allow_byok:false}};expect((await repository.dryRunCourseManifest(manifest)).valid).toBe(true);const first=await repository.importCourseManifest(manifest,"create initial demo course manifest");expect((await repository.publishCourseManifest(first.course_id,first.manifest_version,"publish initial demo course manifest")).state).toBe("published");const second=await repository.importCourseManifest({...manifest,experiment:{...manifest.experiment,spec_version:"v2"}},"create revised demo course manifest");await repository.publishCourseManifest(second.course_id,second.manifest_version,"publish revised demo course manifest");expect((await repository.rollbackCourseManifest(first.course_id,first.manifest_version,"restore initial demo course manifest")).rollback_of).toBe(first.manifest_version);const enrollment=await repository.importEnrollmentCsv({course_id:first.course_id,csv:"username,display_name,role,group\ndemo-new,Demo New,student,Team A\n",dry_run:false,reason:"apply demo enrollment import"});expect(enrollment.updated_memberships).toBe(1);expect((await new LocalStoragePortalRepository().courseManifestVersions(first.course_id))[0].state).toBe("published");});
  test("shows model metadata, persists quota changes, and refuses Demo credentials",async()=>{const repository=new LocalStoragePortalRepository();await repository.switchDemoRole("admin");const providers=await repository.modelProviders();expect(providers[0].secret_configured).toBe(true);expect(JSON.stringify(providers)).not.toContain("secret-at");const current=(await repository.modelQuotas())[0];const saved=await repository.saveModelQuota({version:"model-quota-policy-input.v1",course_id:current.course_id,monthly_request_limit:900,monthly_token_limit:900000,monthly_cost_limit_usd:45,enabled:true,expected_revision:current.revision,reason:"update demo monthly model quota"});expect(saved.revision).toBe(current.revision+1);await expect(repository.saveModelProvider({version:"model-provider-input.v1",id:"demo",name:"Demo",kind:"openai-compatible",base_url:"https://model.invalid/v1",models:["demo"],default_model:"demo",secret:"secret-at-least-sixteen",input_cost_per_million_usd:0,output_cost_per_million_usd:0,max_output_tokens:1024,enabled:true,expected_revision:0,reason:"attempt demo provider secret"})).rejects.toThrow("Demo 不保存");});
});
