import { expect,test } from "bun:test";
import { exportJWK,generateKeyPair,SignJWT } from "jose";
import postgres from "postgres";
import { OidcService,consumeOidcAuthorization } from "../server/oidc.ts";

const databaseUrl=process.env.PORTAL_TEST_DATABASE_URL;
const integration=databaseUrl?test:test.skip;

integration("OIDC encrypts secrets and validates signed issuer, audience, nonce, and one-time state",async()=>{
  const sql=postgres(databaseUrl!,{max:4,prepare:false});const prefix=`oidc-${crypto.randomUUID()}`;const admin=`${prefix}-admin`;const state=crypto.randomUUID();const stateHash=new Bun.CryptoHasher("sha256").update(state).digest("hex");const issuer=`https://${prefix}.example.test`;const clientId="portal-test";const callbackUri="https://portal.example.test/api/v1/auth/oidc/callback";const keys=await generateKeyPair("RS256",{extractable:true});const jwk={...await exportJWK(keys.publicKey),kid:"test-key",alg:"RS256",use:"sig"};let nonce="";let tokenMode:"ok"|"bad-audience"|"bad-nonce"|"bad-issuer"="ok";
  try{
    await sql`insert into users(id,username,display_name,role,status) values(${admin},${admin},'OIDC Admin','admin','active')`;
    const key=Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString("base64url");const service=await OidcService.create(sql,key,{fetch:async(input)=>{const url=String(typeof input==="string"||input instanceof URL?input:input.url);if(url===`${issuer}/.well-known/openid-configuration`)return Response.json({issuer,authorization_endpoint:`${issuer}/authorize`,token_endpoint:`${issuer}/token`,jwks_uri:`${issuer}/jwks`,response_types_supported:["code"],subject_types_supported:["public"],id_token_signing_alg_values_supported:["RS256"],token_endpoint_auth_methods_supported:["client_secret_post"],code_challenge_methods_supported:["S256"]});if(url===`${issuer}/jwks`)return Response.json({keys:[jwk]});if(url===`${issuer}/token`){const idToken=await new SignJWT({sub:"subject-1",preferred_username:"oidc.student",name:"OIDC Student",role:"faculty",nonce:tokenMode==="bad-nonce"?"wrong-nonce":nonce}).setProtectedHeader({alg:"RS256",kid:"test-key"}).setIssuer(tokenMode==="bad-issuer"?"https://attacker.example.test":issuer).setAudience(tokenMode==="bad-audience"?"wrong-client":clientId).setIssuedAt().setExpirationTime("5m").sign(keys.privateKey);return Response.json({access_token:"access-token",token_type:"Bearer",expires_in:300,id_token:idToken});}return new Response("unexpected OIDC URL",{status:500});}});const secret=`secret-${crypto.randomUUID()}`;
    const summary=await service.saveProvider({id:admin,username:admin,display_name:"OIDC Admin",role:"admin"},{version:"oidc-provider-input.v1",id:prefix,name:"Integration OIDC",issuer,client_id:clientId,client_secret:secret,scopes:["openid","profile"],username_claim:"preferred_username",display_name_claim:"name",role_claim:"role",role_mappings:{faculty:"teacher"},default_role:"student",enabled:true,reason:"integration provider encryption test"},`trace-${crypto.randomUUID()}`);
    expect(summary.secret_configured).toBe(true);expect(JSON.stringify(summary)).not.toContain(secret);const stored=(await sql`select client_secret_cipher,client_secret_iv from oidc_providers where id=${prefix}`)[0];expect(Buffer.from(stored.client_secret_cipher).toString("utf8")).not.toContain(secret);expect(Buffer.from(stored.client_secret_iv).byteLength).toBe(12);
    await sql`insert into oidc_authorizations(id,provider_id,state_hash,flow_cipher,flow_iv,return_to,expires_at) values(${`${prefix}-flow`},${prefix},${stateHash},${new Uint8Array([1])},${new Uint8Array(12)},'/workspace',now()+interval '5 minutes')`;
    expect((await consumeOidcAuthorization(sql,prefix,state)).provider_id).toBe(prefix);await expect(consumeOidcAuthorization(sql,prefix,state)).rejects.toThrow("already consumed");
    let lastCallback=new URL(callbackUri);async function callback(mode:typeof tokenMode){tokenMode=mode;const authorization=await service.start(prefix,callbackUri,"/workspace");nonce=authorization.searchParams.get("nonce")??"";lastCallback=new URL(callbackUri);lastCallback.searchParams.set("code",`code-${mode}`);lastCallback.searchParams.set("state",authorization.searchParams.get("state")??"");return service.callback(prefix,lastCallback);}
    const loggedIn=await callback("ok");expect(loggedIn.actor.role).toBe("teacher");expect(loggedIn.return_to).toBe("/workspace");await expect(service.callback(prefix,lastCallback)).rejects.toThrow("already consumed");await expect(callback("bad-audience")).rejects.toThrow();await expect(callback("bad-nonce")).rejects.toThrow();await expect(callback("bad-issuer")).rejects.toThrow();
  }finally{await sql`delete from oidc_authorizations where provider_id=${prefix}`;await sql`delete from sessions where user_id in (select id from users where oidc_issuer=${issuer})`;await sql`delete from audit_events where actor_id=${admin} or actor_id in (select id from users where oidc_issuer=${issuer})`;await sql`delete from users where oidc_issuer=${issuer}`;await sql`delete from oidc_providers where id=${prefix}`;await sql`delete from users where id=${admin}`;await sql.end({timeout:5});}
},30_000);
