import { expect,test } from "bun:test";
import postgres from "postgres";
import { PostgresPortalRepository } from "../server/postgres-repository.ts";
import { GiteaClient } from "../storage/gitea.ts";
import { provisionOne } from "../worker/worker.ts";

const databaseUrl=process.env.PORTAL_TEST_DATABASE_URL;
const giteaUrl=process.env.PORTAL_TEST_GITEA_URL;
const integration=databaseUrl&&giteaUrl?test:test.skip;

integration("real Gitea provisioning and signed push webhook reach the project commit ledger",async()=>{
  const sql=postgres(databaseUrl!,{max:8,prepare:false});const token=process.env.PORTAL_TEST_GITEA_TOKEN!;const username=process.env.PORTAL_TEST_GITEA_USERNAME!;const suffix=crypto.randomUUID().slice(0,8);const prefix=`gitea-project-${suffix}`;const teacher=`${prefix}-teacher`;const student=`${prefix}-student`;const course=`${prefix}-course`;const experiment=`${prefix}-experiment`;const stage=`${prefix}-stage`;const template=`template-${suffix}`;const organization=`course-${suffix}`;const repositoryName=`team-${suffix}`;let projectId="";
  const request=async(pathname:string,init:RequestInit={})=>{const response=await fetch(new URL(pathname,`${giteaUrl!.replace(/\/$/,"")}/`),{...init,headers:{authorization:`token ${token}`,accept:"application/json",...(init.body?{"content-type":"application/json"}:{}),...init.headers}});if(!response.ok)throw new Error(`Gitea project integration HTTP ${response.status}: ${(await response.text()).slice(0,500)}`);return response;};
  try{
    await request("/api/v1/user/repos",{method:"POST",body:JSON.stringify({name:template,description:"VOS project template",private:true,template:true,auto_init:true,default_branch:"main"})});await request("/api/v1/orgs",{method:"POST",body:JSON.stringify({username:organization,full_name:"VOS project course",visibility:"private"})});
    await sql.begin(async tx=>{await tx`insert into users(id,username,display_name,role,status) values(${teacher},${teacher},'Gitea Teacher','teacher','active'),(${student},${username},'Gitea Student','student','active')`;await tx`insert into courses(id,code,name,term,status) values(${course},${prefix},'Gitea Course','test','active')`;await tx`insert into course_memberships(course_id,user_id,role,status,source) values(${course},${student},'student','active','manual')`;await tx`insert into experiments(id,course_id,title,spec_version,publish_state) values(${experiment},${course},'Gitea Lab','v1','published')`;await tx`insert into stage_gates(id,experiment_id,key,name,sequence,status,config) values(${stage},${experiment},'seed','Seed',0,'open',${tx.json({required_artifacts:[],required_evidence:[],manual_review_required:false})})`;});
    const portal=new PostgresPortalRepository(sql);const created=await portal.createProject({id:teacher,username:teacher,display_name:"Teacher",role:"teacher"},{version:"project-provision-request.v1",experiment_id:experiment,member_ids:[student],owner:organization,repository:repositoryName,template_owner:username,template_repository:template,description:"Real Gitea provisioned project",private:true,reason:"create real Gitea integration project"},`key-${suffix}`,`hash-${suffix}`,`trace-${suffix}`);projectId=created.project_id;
    expect(await provisionOne(sql,new GiteaClient(giteaUrl!,token),`worker-${suffix}`,"http://vos-portal:8787/api/v1/internal/gitea/webhook",process.env.PORTAL_TEST_GITEA_WEBHOOK_SECRET!)).toBe(true);expect((await portal.projectProvisioning({id:teacher,username:teacher,display_name:"Teacher",role:"teacher"},projectId)).status).toBe("active");const repository=await (await request(`/api/v1/repos/${organization}/${repositoryName}`)).json() as {default_branch:string};
    await request(`/api/v1/repos/${organization}/${repositoryName}/contents/push-${suffix}.txt`,{method:"POST",body:JSON.stringify({branch:repository.default_branch,content:Buffer.from("signed webhook integration\n").toString("base64"),message:"test: trigger signed Portal webhook"})});
    const deadline=Date.now()+15_000;let ledger=0;while(Date.now()<deadline){ledger=Number((await sql`select count(*)::int count from project_commit_ledger where project_id=${projectId}`)[0].count);if(ledger>0)break;await Bun.sleep(250);}expect(ledger).toBe(1);expect(Number((await sql`select count(*)::int count from notifications where user_id=${student} and title='仓库收到新的 push'`)[0].count)).toBe(1);
  }finally{
    await sql`delete from notifications where user_id in (${teacher},${student})`;await sql`delete from project_commit_ledger where project_id=${projectId||"missing"}`;await sql`delete from gitea_webhook_deliveries where repository_full_name=${`${organization}/${repositoryName}`}`;await sql`delete from audit_events where resource_id=${projectId||"missing"} or actor_id=${teacher}`;await sql`delete from outbox_events where aggregate_id=${projectId||"missing"}`;await sql`delete from idempotency_keys where actor_id=${teacher}`;await sql`delete from project_repositories where project_id=${projectId||"missing"}`;await sql`delete from project_members where project_id=${projectId||"missing"}`;await sql`delete from projects where id=${projectId||"missing"}`;await sql`delete from stage_gates where id=${stage}`;await sql`delete from experiments where id=${experiment}`;await sql`delete from course_memberships where course_id=${course}`;await sql`delete from courses where id=${course}`;await sql`delete from users where id in (${teacher},${student})`;await sql.end({timeout:5});await request(`/api/v1/repos/${organization}/${repositoryName}`,{method:"DELETE"}).catch(()=>undefined);await request(`/api/v1/orgs/${organization}`,{method:"DELETE"}).catch(()=>undefined);await request(`/api/v1/repos/${username}/${template}`,{method:"DELETE"}).catch(()=>undefined);
  }
},45_000);
