import { expect,test } from "bun:test";
import postgres from "postgres";
import { PostgresPortalRepository } from "../server/postgres-repository.ts";
import { GiteaClient } from "../storage/gitea.ts";
import { MAX_PROVISION_ATTEMPTS,provisionOne } from "../worker/worker.ts";

const databaseUrl=process.env.PORTAL_TEST_DATABASE_URL;
const integration=databaseUrl?test:test.skip;

integration("project creation, Gitea outbox provisioning and push ledger are transactional",async()=>{
  const sql=postgres(databaseUrl!,{max:12,prepare:false});const prefix=`provision-${crypto.randomUUID()}`;const teacher=`${prefix}-teacher`;const student=`${prefix}-student`;const outsider=`${prefix}-outsider`;const course=`${prefix}-course`;const experiment=`${prefix}-experiment`;const stage=`${prefix}-stage`;let projectId="";let failedProjectId="";const delivery=`${prefix}-delivery`;
  const actor={id:teacher,username:teacher,display_name:"Provision Teacher",role:"teacher" as const};
  try{
    await sql.begin(async tx=>{await tx`insert into users(id,username,display_name,role,status) values(${teacher},${teacher},'Provision Teacher','teacher','active'),(${student},${student},'Provision Student','student','active'),(${outsider},${outsider},'Provision Outsider','student','active')`;await tx`insert into courses(id,code,name,term,status) values(${course},${prefix},'Provision Course','test','active')`;await tx`insert into course_memberships(course_id,user_id,role,status,source) values(${course},${student},'student','active','manual')`;await tx`insert into experiments(id,course_id,title,spec_version,publish_state) values(${experiment},${course},'Provision Lab','v1','published')`;await tx`insert into stage_gates(id,experiment_id,key,name,sequence,status,config) values(${stage},${experiment},'seed','Seed',0,'open',${tx.json({required_artifacts:[],required_evidence:[],manual_review_required:false})})`;});
    const repository=new PostgresPortalRepository(sql);expect((await repository.projectProvisionOptions(actor)).members.map(item=>item.id)).toContain(student);expect((await repository.projectProvisionOptions(actor)).members.map(item=>item.id)).not.toContain(outsider);const request={version:"project-provision-request.v1" as const,experiment_id:experiment,member_ids:[student],owner:"course",repository:`team-${prefix.slice(-8)}`,template_owner:"templates",template_repository:"xv6",description:"Provision integration project",private:true as const,reason:"create integration teaching project"};const created=await Promise.all(Array.from({length:4},()=>repository.createProject(actor,request,"same-project-key","same-project-hash",`${prefix}-trace`)));projectId=created[0].project_id;expect(new Set(created.map(item=>item.project_id)).size).toBe(1);expect(created[0].status).toBe("queued");await expect(repository.createProject(actor,{...request,member_ids:[outsider],repository:`outsider-${prefix.slice(-8)}`},"outsider-project-key","outsider-project-hash",`${prefix}-outsider-trace`)).rejects.toThrow("活跃学生");await expect(repository.projectBinding({id:student,username:student,display_name:"Student",role:"student"},projectId)).rejects.toThrow("尚未供应完成");await expect(repository.projectProvisioning({id:outsider,username:outsider,display_name:"Outsider",role:"student"},projectId)).rejects.toThrow("不可见");
    const provisioned={id:42,full_name:`course/${request.repository}`,html_url:`https://git.example/course/${request.repository}`,clone_url:`https://git.example/course/${request.repository}.git`,private:true};const transport=async(input:URL|RequestInfo,init?:RequestInit)=>{const url=new URL(String(input));if(url.pathname===`/api/v1/repos/course/${request.repository}`&&!init?.method)return new Response(null,{status:404});if(url.pathname.includes("/generate"))return Response.json(provisioned,{status:201});if(url.pathname.includes("/collaborators/"))return new Response(null,{status:204});if(url.pathname.endsWith("/hooks")&&!init?.method)return Response.json([]);if(url.pathname.endsWith("/hooks")&&init?.method==="POST")return Response.json({id:1},{status:201});throw new Error(`unexpected Gitea request ${init?.method??"GET"} ${url.pathname}`);};
    expect(await provisionOne(sql,new GiteaClient("http://gitea:3000","token",transport as typeof fetch),"worker-it","http://vos-portal:8787/api/v1/internal/gitea/webhook","webhook-secret")).toBe(true);expect((await repository.projectProvisioning(actor,projectId)).status).toBe("active");expect((await repository.projectBinding({id:student,username:student,display_name:"Student",role:"student"},projectId)).repo_url).toBe(provisioned.clone_url);expect((await sql`select published_at is not null published from outbox_events where topic='project.provision.requested' and aggregate_id=${projectId}`)[0].published).toBe(true);
    const push={delivery_id:delivery,event_type:"push" as const,repository_full_name:provisioned.full_name,ref_name:"refs/heads/main",before_sha:"a".repeat(40),after_sha:"b".repeat(40),pusher_username:student,payload:{ref:"refs/heads/main",after:"b".repeat(40)}};expect(await repository.recordGiteaWebhook(push,`${prefix}-push-trace`)).toBe(true);expect(await repository.recordGiteaWebhook(push,`${prefix}-push-trace-duplicate`)).toBe(false);expect(Number((await sql`select count(*)::int count from project_commit_ledger where project_id=${projectId}`)[0].count)).toBe(1);expect(Number((await sql`select count(*)::int count from notifications where user_id=${student} and title='仓库收到新的 push'`)[0].count)).toBe(1);
    const failedRequest={...request,repository:`fail-${prefix.slice(-8)}`,reason:"verify terminal provisioning failure and retry"};failedProjectId=(await repository.createProject(actor,failedRequest,"failed-project-key","failed-project-hash",`${prefix}-failed-trace`)).project_id;const failingTransport=async()=>new Response("upstream unavailable",{status:503});const failingGitea=new GiteaClient("http://gitea:3000","token",failingTransport as typeof fetch);for(let attempt=1;attempt<=MAX_PROVISION_ATTEMPTS;attempt+=1){expect(await provisionOne(sql,failingGitea,"worker-failure-it","http://vos-portal:8787/api/v1/internal/gitea/webhook","webhook-secret")).toBe(true);if(attempt<MAX_PROVISION_ATTEMPTS)await sql`update outbox_events set next_attempt_at=now() where topic='project.provision.requested' and aggregate_id=${failedProjectId}`;}const teacherFailure=await repository.projectProvisioning(actor,failedProjectId);expect(teacherFailure.status).toBe("failed");expect(teacherFailure.last_error).toContain("HTTP 503");const studentFailure=await repository.projectProvisioning({id:student,username:student,display_name:"Student",role:"student"},failedProjectId);expect(studentFailure.last_error).toBe("仓库供应失败，请联系课程团队");expect((await sql`select next_attempt_at='infinity'::timestamptz terminal from outbox_events where aggregate_id=${failedProjectId}`)[0].terminal).toBe(true);const retried=await repository.retryProjectProvisioning(actor,failedProjectId,"teacher approved a controlled provisioning retry",`${prefix}-retry-trace`,"retry-key","retry-hash");expect(retried.status).toBe("queued");expect((await repository.retryProjectProvisioning(actor,failedProjectId,"teacher approved a controlled provisioning retry",`${prefix}-retry-trace-duplicate`,"retry-key","retry-hash")).status).toBe("queued");expect((await sql`select next_attempt_at<=now() ready from outbox_events where aggregate_id=${failedProjectId}`)[0].ready).toBe(true);
  }finally{
    const projectIds=[projectId,failedProjectId].filter(Boolean);await sql`delete from notifications where user_id in (${teacher},${student},${outsider})`;await sql`delete from project_commit_ledger where project_id in ${sql(projectIds.length?projectIds:["missing"])}`;await sql`delete from gitea_webhook_deliveries where delivery_id=${delivery}`;await sql`delete from audit_events where resource_id in ${sql(projectIds.length?projectIds:["missing"])} or actor_id=${teacher}`;await sql`delete from outbox_events where aggregate_id in ${sql(projectIds.length?projectIds:["missing"])}`;await sql`delete from idempotency_keys where actor_id=${teacher}`;await sql`delete from project_repositories where project_id in ${sql(projectIds.length?projectIds:["missing"])}`;await sql`delete from project_members where project_id in ${sql(projectIds.length?projectIds:["missing"])}`;await sql`delete from projects where id in ${sql(projectIds.length?projectIds:["missing"])}`;await sql`delete from stage_gates where id=${stage}`;await sql`delete from experiments where id=${experiment}`;await sql`delete from course_memberships where course_id=${course}`;await sql`delete from courses where id=${course}`;await sql`delete from users where id in (${teacher},${student},${outsider})`;await sql.end({timeout:5});
  }
},30_000);
