import { createHmac, timingSafeEqual } from "node:crypto";

export interface GiteaRepositoryRequest {owner:string;name:string;template_owner:string;template_repo:string;description:string;private:boolean;collaborators:string[];webhook_url:string;webhook_secret:string}
export interface GiteaRepository {id:number;full_name:string;html_url:string;clone_url:string;private:boolean}

export class GiteaClient {
  constructor(private readonly baseUrl:string,private readonly token:string,private readonly transport:typeof fetch=fetch){const url=new URL(baseUrl);if(url.protocol!=="https:"&&!isInternalHttp(url))throw new Error("Gitea URL must use HTTPS outside an internal hostname");if(!token.trim())throw new Error("Gitea token is required");}
  static fromEnv(transport:typeof fetch=fetch):GiteaClient{return new GiteaClient(required("VOS_GITEA_URL"),required("VOS_GITEA_TOKEN"),transport);}
  async health():Promise<string>{const value=await this.request<{version?:unknown}>("/api/v1/version");if(typeof value.version!=="string"||!value.version)throw new Error("Gitea version response is invalid");return value.version;}
  async provision(input:GiteaRepositoryRequest):Promise<GiteaRepository>{validateSegment(input.owner,"owner");validateSegment(input.name,"name");let created=false;let repository=await this.getRepository(input.owner,input.name);if(repository){if(repository.private!==input.private)throw new Error("existing Gitea repository privacy does not match requested binding");}else{repository=await this.request<GiteaRepository>(`/api/v1/repos/${encodeURIComponent(input.template_owner)}/${encodeURIComponent(input.template_repo)}/generate`,{method:"POST",body:JSON.stringify({owner:input.owner,name:input.name,description:input.description,private:input.private,git_content:true})});created=true;}try{for(const username of [...new Set(input.collaborators)].sort()){validateSegment(username,"collaborator");await this.request(`/api/v1/repos/${encodeURIComponent(input.owner)}/${encodeURIComponent(input.name)}/collaborators/${encodeURIComponent(username)}`,{method:"PUT",body:JSON.stringify({permission:"push"})});}await this.ensureWebhook(input);return repository;}catch(error){if(created)await this.request(`/api/v1/repos/${encodeURIComponent(input.owner)}/${encodeURIComponent(input.name)}`,{method:"DELETE"}).catch(rollback=>{throw new AggregateError([error,rollback],"Gitea provisioning and rollback both failed");});throw error;}}
  private async getRepository(owner:string,name:string):Promise<GiteaRepository|undefined>{const response=await this.raw(`/api/v1/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}`);if(response.status===404)return undefined;if(!response.ok)throw await failure(response);return await response.json() as GiteaRepository;}
  private async ensureWebhook(input:GiteaRepositoryRequest):Promise<void>{const hooks=await this.request<Array<{id:number;config?:{url?:string}}>>(`/api/v1/repos/${encodeURIComponent(input.owner)}/${encodeURIComponent(input.name)}/hooks`);if(hooks.some(hook=>hook.config?.url===input.webhook_url))return;await this.request(`/api/v1/repos/${encodeURIComponent(input.owner)}/${encodeURIComponent(input.name)}/hooks`,{method:"POST",body:JSON.stringify({type:"gitea",active:true,events:["push"],config:{url:input.webhook_url,content_type:"json",secret:input.webhook_secret}})});}
  private async request<T=unknown>(pathname:string,init:RequestInit={}):Promise<T>{const response=await this.raw(pathname,init);if(!response.ok)throw await failure(response);if(response.status===204)return undefined as T;return await response.json() as T;}
  private raw(pathname:string,init:RequestInit={}):Promise<Response>{return this.transport(new URL(pathname,`${this.baseUrl.replace(/\/$/,"")}/`),{...init,headers:{authorization:`token ${this.token}`,accept:"application/json",...(init.body?{"content-type":"application/json"}:{}),...init.headers}});}
}

export function verifyGiteaWebhook(body:Uint8Array,signature:string|null,secret:string):boolean{if(!signature||!/^[0-9a-f]{64}$/i.test(signature))return false;const expected=createHmac("sha256",secret).update(body).digest();const actual=Buffer.from(signature,"hex");return actual.length===expected.length&&timingSafeEqual(actual,expected);}
function required(name:string):string{const value=process.env[name];if(!value)throw new Error(`${name} is required`);return value;}
function validateSegment(value:string,label:string):void{if(!/^[a-zA-Z0-9_.-]{1,100}$/.test(value)||value==="."||value==="..")throw new Error(`invalid Gitea ${label}`);}
function isInternalHttp(url:URL):boolean{return url.protocol==="http:"&&(url.hostname==="localhost"||url.hostname==="127.0.0.1"||!url.hostname.includes("."));}
async function failure(response:Response):Promise<Error>{const text=(await response.text()).slice(0,500);return new Error(`Gitea HTTP ${response.status}${text?`: ${text}`:""}`);}
